import type { Unit } from '../types.js';

// A1: глагол to be, there is/are, Present Simple, исчисляемые/неисчисляемые, Present Continuous,
// повелительное наклонение, сравнение Present Simple и Continuous, степени сравнения.
export const A1: Unit[] = [
  {
    id: 'people',
    title: 'People and countries',
    ru: 'Люди и страны',
    level: 'A1',
    grades: [5, 7],
    icon: '🌍',
    words: [
      ['country', 'страна', '🗺️'],
      ['city', 'город', '🏙️'],
      ['Russia', 'Россия', '🇷🇺'],
      ['Russian', 'русский'],
      ['England', 'Англия', '🏴'],
      ['English', 'английский'],
      ['France', 'Франция', '🇫🇷'],
      ['French', 'французский'],
      ['China', 'Китай', '🇨🇳'],
      ['Chinese', 'китайский'],
      ['Italy', 'Италия', '🇮🇹'],
      ['Italian', 'итальянский'],
      ['doctor', 'врач', '🧑‍⚕️'],
      ['driver', 'водитель', '🚕'],
      ['cook', 'повар', '🧑‍🍳'],
      ['farmer', 'фермер', '🧑‍🌾'],
      ['student', 'студент', '🧑‍🎓'],
      ['singer', 'певец', '🧑‍🎤'],
      ['job', 'работа, профессия'],
      ['from', 'из (откуда)'],
    ],
    phrases: [
      ['Where are you from?', 'Откуда ты?'],
      ['I am from Russia.', 'Я из России.'],
      ['She is not English, she is French.', 'Она не англичанка, она француженка.'],
      ['What is his job?', 'Кем он работает?'],
      ['He is a doctor.', 'Он врач.'],
      ['Are they students?', 'Они студенты?'],
      ['No, they aren’t.', 'Нет.'],
      ['We are in Moscow.', 'Мы в Москве.'],
      ['Is your mum a teacher?', 'Твоя мама учитель?'],
      ['It is a big city.', 'Это большой город.'],
    ],
    grammar: {
      title: 'Глагол to be: am, is, are',
      rule: ['I am, he / she / it is, we / you / they are.', 'Отрицание: I’m not, he isn’t, they aren’t.', 'Вопрос: Is she a doctor? — Yes, she is. / No, she isn’t. Are you from Italy?', 'Где? Откуда? — Where are you from? I’m from Russia.'],
      gaps: [
        ['She ___ a singer.', ['is', 'are', 'am'], 0, 'Она певица.'],
        ['They ___ from China.', ['are', 'is', 'am'], 0, 'Они из Китая.'],
        ['I ___ not a student.', ['am', 'is', 'are'], 0, 'Я не студент.'],
        ['___ he a driver?', ['Is', 'Are', 'Am'], 0, 'Он водитель?'],
        ['We ___ in London.', ['are', 'is', 'am'], 0, 'Мы в Лондоне.'],
        ['My parents ___ doctors.', ['are', 'is', 'am'], 0, 'Мои родители — врачи.'],
        ['Is she French? — No, she ___.', ['isn’t', 'aren’t', 'not'], 0, 'Нет.'],
        ['Where ___ you from?', ['are', 'is', 'do'], 0, 'Откуда ты?'],
        ['Tom ___ English.', ['is', 'are', 'be'], 0, 'Том — англичанин.'],
        ['Are you Italian? — Yes, I ___.', ['am', 'are', 'is'], 0, 'Да.'],
      ],
    },
  },
  {
    id: 'school',
    title: 'At school',
    ru: 'В школе',
    level: 'A1',
    grades: [5, 7],
    icon: '🏫',
    words: [
      ['classroom', 'класс (комната)'],
      ['board', 'доска'],
      ['lesson', 'урок'],
      ['break', 'перемена'],
      ['timetable', 'расписание', '🗓️'],
      ['homework', 'домашнее задание', '📝'],
      ['test', 'контрольная'],
      ['maths', 'математика', '➗'],
      ['science', 'естествознание', '🔬'],
      ['history', 'история', '🏛️'],
      ['geography', 'география', '🌍'],
      ['art', 'рисование', '🎨'],
      ['music', 'музыка', '🎵'],
      ['PE', 'физкультура', '🏀'],
      ['library', 'библиотека', '📚'],
      ['gym', 'спортзал'],
      ['canteen', 'столовая'],
      ['notebook', 'тетрадь', '📓'],
      ['scissors', 'ножницы', '✂️'],
      ['dictionary', 'словарь'],
    ],
    phrases: [
      ['There is a board in our classroom.', 'В нашем классе есть доска.'],
      ['There are twenty desks.', 'Здесь двадцать парт.'],
      ['Is there a library in your school?', 'В твоей школе есть библиотека?'],
      ['My favourite subject is maths.', 'Мой любимый предмет — математика.'],
      ['We have PE on Monday.', 'В понедельник у нас физкультура.'],
      ['The book is on the desk.', 'Книга на парте.'],
      ['The bag is under the chair.', 'Рюкзак под стулом.'],
      ['Open your notebooks, please.', 'Откройте тетради, пожалуйста.'],
      ['Can I go out, please?', 'Можно выйти?'],
      ['The canteen is next to the gym.', 'Столовая рядом со спортзалом.'],
    ],
    grammar: {
      title: 'there is / there are и предлоги места',
      rule: ['There is + один предмет: There is a board. There are + много: There are two windows.', 'Вопрос: Is there…? Are there…? Нет: There isn’t / There aren’t any…', 'in — в, on — на, under — под, next to — рядом с, between — между, behind — за, in front of — перед.'],
      gaps: [
        ['There ___ a computer in the classroom.', ['is', 'are', 'be'], 0, 'В классе есть компьютер.'],
        ['There ___ three windows.', ['are', 'is', 'am'], 0, 'Здесь три окна.'],
        ['___ there a gym in your school?', ['Is', 'Are', 'Do'], 0, 'В твоей школе есть спортзал?'],
        ['___ there any books on the desk?', ['Are', 'Is', 'Do'], 0, 'На парте есть книги?'],
        ['There ___ any pens in my bag.', ['aren’t', 'isn’t', 'not'], 0, 'В моём рюкзаке нет ручек.'],
        ['The cat is ___ the box. (внутри)', ['in', 'on', 'under'], 0, 'Кошка в коробке.'],
        ['The book is ___ the desk. (сверху)', ['on', 'in', 'under'], 0, 'Книга на парте.'],
        ['The ball is ___ the chair. (снизу)', ['under', 'on', 'in'], 0, 'Мяч под стулом.'],
        ['The shop is ___ the bank and the cafe.', ['between', 'next', 'behind of'], 0, 'Магазин между банком и кафе.'],
        ['The board is ___ the pupils. (перед)', ['in front of', 'front', 'before of'], 0, 'Доска перед учениками.'],
      ],
    },
  },
  {
    id: 'home',
    title: 'My home',
    ru: 'Мой дом',
    level: 'A1',
    grades: [5, 7],
    icon: '🛋️',
    words: [
      ['flat', 'квартира', '🏢'],
      ['room', 'комната'],
      ['kitchen', 'кухня', '🍳'],
      ['bedroom', 'спальня', '🛏️'],
      ['bathroom', 'ванная', '🛁'],
      ['living room', 'гостиная', '🛋️'],
      ['garden', 'сад', '🌳'],
      ['window', 'окно', '🪟'],
      ['door', 'дверь', '🚪'],
      ['wall', 'стена', '🧱'],
      ['floor', 'пол, этаж'],
      ['bed', 'кровать'],
      ['sofa', 'диван'],
      ['table', 'стол'],
      ['lamp', 'лампа', '💡'],
      ['shelf', 'полка'],
      ['fridge', 'холодильник', '🧊'],
      ['carpet', 'ковёр'],
      ['mirror', 'зеркало', '🪞'],
      ['picture', 'картина', '🖼️'],
    ],
    phrases: [
      ['I live in a flat.', 'Я живу в квартире.'],
      ['Our flat is on the fifth floor.', 'Наша квартира на пятом этаже.'],
      ['These are my books.', 'Это мои книги.'],
      ['Those pictures are beautiful.', 'Вон те картины красивые.'],
      ['There is a lamp on the table.', 'На столе лампа.'],
      ['My bedroom is small but nice.', 'Моя спальня маленькая, но уютная.'],
      ['The fridge is in the kitchen.', 'Холодильник на кухне.'],
      ['Close the door, please.', 'Закрой дверь, пожалуйста.'],
      ['We have got a garden.', 'У нас есть сад.'],
      ['Whose room is this?', 'Чья это комната?'],
    ],
    grammar: {
      title: 'this / these, that / those',
      rule: ['Рядом: this (один) — these (много): this lamp, these lamps.', 'Далеко: that (один) — those (много): that door, those doors.', 'Глагол тоже меняется: This is… / These are…'],
      gaps: [
        ['___ are my books. (рядом)', ['These', 'This', 'That'], 0, 'Это мои книги.'],
        ['___ is my bedroom. (рядом)', ['This', 'These', 'Those'], 0, 'Это моя спальня.'],
        ['___ pictures are old. (вон те)', ['Those', 'That', 'This'], 0, 'Вон те картины старые.'],
        ['___ house is big. (вон тот)', ['That', 'Those', 'These'], 0, 'Вон тот дом большой.'],
        ['These ___ my parents.', ['are', 'is', 'am'], 0, 'Это мои родители.'],
        ['That ___ our garden.', ['is', 'are', 'am'], 0, 'Вон там наш сад.'],
        ['Look at ___ birds in the sky!', ['those', 'that', 'this'], 0, 'Посмотри на тех птиц в небе!'],
        ['Are ___ your shoes? (рядом)', ['these', 'this', 'that'], 0, 'Это твоя обувь?'],
        ['Is ___ your phone? (рядом)', ['this', 'these', 'those'], 0, 'Это твой телефон?'],
        ['I like ___ sofa. (вон тот)', ['that', 'those', 'these'], 0, 'Мне нравится вон тот диван.'],
      ],
    },
  },
  {
    id: 'routine',
    title: 'My day',
    ru: 'Мой день',
    level: 'A1',
    grades: [5, 7],
    icon: '⏰',
    words: [
      ['get up', 'вставать', '⏰'],
      ['wake up', 'просыпаться'],
      ['have breakfast', 'завтракать', '🥣'],
      ['have lunch', 'обедать'],
      ['have dinner', 'ужинать', '🍽️'],
      ['go to school', 'ходить в школу', '🏫'],
      ['go home', 'идти домой'],
      ['go to bed', 'ложиться спать', '🛏️'],
      ['brush teeth', 'чистить зубы', '🪥'],
      ['take a shower', 'принимать душ', '🚿'],
      ['get dressed', 'одеваться'],
      ['do homework', 'делать уроки', '📝'],
      ['watch TV', 'смотреть телевизор', '📺'],
      ['morning', 'утро', '🌅'],
      ['afternoon', 'день (после полудня)'],
      ['evening', 'вечер', '🌆'],
      ['o’clock', 'ровно (о времени)'],
      ['half past', 'половина (после часа)'],
      ['quarter', 'четверть'],
      ['every day', 'каждый день'],
    ],
    phrases: [
      ['I get up at seven o’clock.', 'Я встаю в семь часов.'],
      ['She goes to school by bus.', 'Она ездит в школу на автобусе.'],
      ['We have dinner at six.', 'Мы ужинаем в шесть.'],
      ['He doesn’t watch TV in the morning.', 'Он не смотрит телевизор утром.'],
      ['My dad works in an office.', 'Мой папа работает в офисе.'],
      ['I do my homework in the evening.', 'Я делаю уроки вечером.'],
      ['It is half past eight.', 'Половина девятого.'],
      ['My sister takes a shower every morning.', 'Моя сестра каждое утро принимает душ.'],
      ['They don’t go to school on Sunday.', 'В воскресенье они не ходят в школу.'],
      ['I go to bed at ten.', 'Я ложусь спать в десять.'],
    ],
    grammar: {
      title: 'Present Simple: утверждение и отрицание',
      rule: ['Делаю регулярно: I / you / we / they play. he / she / it plays (+s).', '+es после o, s, sh, ch, x: goes, watches, washes. Согласная + y → ies: study → studies.', 'Отрицание: I don’t play. He doesn’t play (после doesn’t — без -s!).'],
      gaps: [
        ['She ___ up at seven.', ['gets', 'get', 'getting'], 0, 'Она встаёт в семь.'],
        ['They ___ to school every day.', ['go', 'goes', 'going'], 0, 'Они ходят в школу каждый день.'],
        ['My mum ___ tea in the morning.', ['drinks', 'drink', 'drinking'], 0, 'Мама пьёт чай утром.'],
        ['He ___ his teeth twice a day.', ['brushes', 'brush', 'brushs'], 0, 'Он чистит зубы дважды в день.'],
        ['I ___ watch TV in the morning.', ['don’t', 'doesn’t', 'not'], 0, 'Я не смотрю телевизор утром.'],
        ['She ___ like getting up early.', ['doesn’t', 'don’t', 'isn’t'], 0, 'Она не любит рано вставать.'],
        ['My brother ___ English at school.', ['studies', 'studys', 'study'], 0, 'Мой брат учит английский в школе.'],
        ['We ___ dinner at six.', ['have', 'has', 'having'], 0, 'Мы ужинаем в шесть.'],
        ['Dad ___ home at seven.', ['comes', 'come', 'coming'], 0, 'Папа приходит домой в семь.'],
        ['He doesn’t ___ to school on Sunday.', ['go', 'goes', 'going'], 0, 'В воскресенье он не ходит в школу.'],
      ],
    },
  },
  {
    id: 'freetime',
    title: 'Free time',
    ru: 'Свободное время',
    level: 'A1',
    grades: [5, 7],
    icon: '🎮',
    words: [
      ['always', 'всегда'],
      ['usually', 'обычно'],
      ['often', 'часто'],
      ['sometimes', 'иногда'],
      ['never', 'никогда'],
      ['weekend', 'выходные'],
      ['play computer games', 'играть в компьютерные игры', '🎮'],
      ['listen to music', 'слушать музыку', '🎧'],
      ['go shopping', 'ходить по магазинам', '🛍️'],
      ['meet friends', 'встречаться с друзьями'],
      ['play football', 'играть в футбол', '⚽'],
      ['play the guitar', 'играть на гитаре', '🎸'],
      ['take photos', 'фотографировать', '📷'],
      ['go to the cinema', 'ходить в кино', '🎬'],
      ['chess', 'шахматы', '♟️'],
      ['hobby', 'хобби'],
      ['board game', 'настольная игра', '🎲'],
      ['go swimming', 'ходить плавать', '🏊'],
      ['once a week', 'раз в неделю'],
      ['twice a week', 'два раза в неделю'],
    ],
    phrases: [
      ['What do you do at the weekend?', 'Что ты делаешь на выходных?'],
      ['I usually meet my friends.', 'Обычно я встречаюсь с друзьями.'],
      ['Do you play chess?', 'Ты играешь в шахматы?'],
      ['Yes, I do. I play twice a week.', 'Да. Я играю два раза в неделю.'],
      ['Does your sister like music?', 'Твоя сестра любит музыку?'],
      ['She never plays computer games.', 'Она никогда не играет в компьютерные игры.'],
      ['How often do you go swimming?', 'Как часто ты ходишь плавать?'],
      ['I sometimes go to the cinema.', 'Иногда я хожу в кино.'],
      ['He is always happy at the weekend.', 'На выходных он всегда счастлив.'],
      ['What is your hobby?', 'Какое у тебя хобби?'],
    ],
    grammar: {
      title: 'Present Simple: вопросы и «как часто»',
      rule: ['Вопрос: Do you play…? Does she play…? (после does — без -s). Ответ: Yes, I do. / No, she doesn’t.', 'Специальный вопрос: What do you do? Where does he live? How often do you…?', 'always, usually, often, sometimes, never — перед глаголом: I often play. Но после to be: He is always late.'],
      gaps: [
        ['___ you play the guitar?', ['Do', 'Does', 'Are'], 0, 'Ты играешь на гитаре?'],
        ['___ your brother like football?', ['Does', 'Do', 'Is'], 0, 'Твой брат любит футбол?'],
        ['Does she play chess? — Yes, she ___.', ['does', 'do', 'is'], 0, 'Да.'],
        ['Where ___ your friend live?', ['does', 'do', 'is'], 0, 'Где живёт твой друг?'],
        ['What ___ you do at the weekend?', ['do', 'does', 'are'], 0, 'Что ты делаешь на выходных?'],
        ['Does he ___ computer games?', ['play', 'plays', 'playing'], 0, 'Он играет в компьютерные игры?'],
        ['How ___ do you go swimming?', ['often', 'many', 'much'], 0, 'Как часто ты ходишь плавать?'],
        ['I ___ go to the cinema. (иногда)', ['sometimes', 'sometime', 'some times'], 0, 'Иногда я хожу в кино.'],
        ['He is ___ late. (всегда)', ['always', 'never always', 'alway'], 0, 'Он всегда опаздывает.'],
        ['We go to the park ___ a week.', ['once', 'one', 'one time of'], 0, 'Мы ходим в парк раз в неделю.'],
      ],
    },
  },
  {
    id: 'foodshop',
    title: 'Food and drinks',
    ru: 'Еда и напитки',
    level: 'A1',
    grades: [5, 7],
    icon: '🛒',
    words: [
      ['rice', 'рис', '🍚'],
      ['pasta', 'макароны', '🍝'],
      ['meat', 'мясо', '🥩'],
      ['sugar', 'сахар'],
      ['salt', 'соль', '🧂'],
      ['butter', 'сливочное масло', '🧈'],
      ['honey', 'мёд', '🍯'],
      ['coffee', 'кофе', '☕'],
      ['lemon', 'лимон', '🍋'],
      ['grapes', 'виноград', '🍇'],
      ['strawberry', 'клубника', '🍓'],
      ['cucumber', 'огурец', '🥒'],
      ['onion', 'лук', '🧅'],
      ['mushroom', 'гриб', '🍄'],
      ['biscuit', 'печенье', '🍪'],
      ['bottle', 'бутылка', '🍾'],
      ['glass', 'стакан'],
      ['cup', 'чашка'],
      ['plate', 'тарелка'],
      ['menu', 'меню'],
    ],
    phrases: [
      ['There is some milk in the fridge.', 'В холодильнике есть молоко.'],
      ['Are there any eggs?', 'Есть ли яйца?'],
      ['There isn’t any bread.', 'Хлеба нет.'],
      ['How much sugar do you want?', 'Сколько сахара ты хочешь?'],
      ['How many apples do we need?', 'Сколько яблок нам нужно?'],
      ['Can I have a glass of water?', 'Можно мне стакан воды?'],
      ['I would like some tea, please.', 'Я бы хотел чаю, пожалуйста.'],
      ['We need a lot of rice.', 'Нам нужно много риса.'],
      ['There are a few biscuits left.', 'Осталось немного печенья.'],
      ['Could we see the menu, please?', 'Можно нам меню?'],
    ],
    grammar: {
      title: 'Исчисляемые и неисчисляемые: some, any, much, many',
      rule: ['Считаемые (apple → apples) и несчитаемые (milk, rice, sugar — без -s).', 'some — в утверждениях, any — в вопросах и отрицаниях: some milk, any eggs?', 'Сколько: how many + считаемые (apples), how much + несчитаемые (sugar). a lot of — много, подходит для всех.'],
      gaps: [
        ['There is ___ juice in the glass.', ['some', 'any', 'a'], 0, 'В стакане есть сок.'],
        ['Is there ___ cheese?', ['any', 'some', 'many'], 0, 'Есть сыр?'],
        ['How ___ sugar do you take?', ['much', 'many', 'often'], 0, 'Сколько сахара ты кладёшь?'],
        ['How ___ eggs do we need?', ['many', 'much', 'lot'], 0, 'Сколько яиц нам нужно?'],
        ['There aren’t ___ grapes.', ['any', 'some', 'much'], 0, 'Винограда нет.'],
        ['I don’t drink ___ coffee.', ['much', 'many', 'a few'], 0, 'Я не пью много кофе.'],
        ['There are ___ of strawberries.', ['a lot', 'much', 'many'], 0, 'Здесь много клубники.'],
        ['Can I have ___ glass of milk?', ['a', 'an', 'some'], 0, 'Можно стакан молока?'],
        ['We need ___ onions for the soup.', ['some', 'any', 'much'], 0, 'Для супа нам нужен лук.'],
        ['There ___ some butter on the plate.', ['is', 'are', 'be'], 0, 'На тарелке есть масло.'],
      ],
    },
  },
  {
    id: 'clothes',
    title: 'Clothes and shopping',
    ru: 'Одежда и покупки',
    level: 'A1',
    grades: [5, 7],
    icon: '👕',
    words: [
      ['T-shirt', 'футболка', '👕'],
      ['jeans', 'джинсы', '👖'],
      ['dress', 'платье', '👗'],
      ['skirt', 'юбка'],
      ['jacket', 'куртка', '🧥'],
      ['coat', 'пальто'],
      ['jumper', 'свитер'],
      ['shoes', 'туфли', '👞'],
      ['trainers', 'кроссовки', '👟'],
      ['boots', 'ботинки', '🥾'],
      ['hat', 'шляпа', '👒'],
      ['cap', 'кепка', '🧢'],
      ['scarf', 'шарф', '🧣'],
      ['gloves', 'перчатки', '🧤'],
      ['socks', 'носки', '🧦'],
      ['shop', 'магазин', '🏪'],
      ['price', 'цена', '🏷️'],
      ['cheap', 'дешёвый'],
      ['expensive', 'дорогой'],
      ['size', 'размер'],
    ],
    phrases: [
      ['I am wearing a blue jumper.', 'На мне синий свитер.'],
      ['What are you doing now?', 'Что ты сейчас делаешь?'],
      ['She is trying on a dress.', 'Она примеряет платье.'],
      ['How much is this jacket?', 'Сколько стоит эта куртка?'],
      ['It is too expensive.', 'Это слишком дорого.'],
      ['Can I try it on?', 'Можно примерить?'],
      ['What size are you?', 'Какой у вас размер?'],
      ['They are not buying anything.', 'Они ничего не покупают.'],
      ['Are you looking for trainers?', 'Вы ищете кроссовки?'],
      ['I’ll take it.', 'Беру.'],
    ],
    grammar: {
      title: 'Present Continuous: происходит сейчас',
      rule: ['am / is / are + глагол с -ing: I am reading. She is wearing a dress.', 'Отрицание: I’m not playing, he isn’t sleeping. Вопрос: Are you listening? What is she doing?', 'Слова-подсказки: now, right now, at the moment, Look! Listen!', 'Правописание: make → making, swim → swimming, lie → lying.'],
      gaps: [
        ['Look! She ___ a new dress.', ['is wearing', 'wears', 'are wearing'], 0, 'Смотри! На ней новое платье.'],
        ['I ___ for my gloves right now.', ['am looking', 'look', 'is looking'], 0, 'Я сейчас ищу перчатки.'],
        ['They ___ TV at the moment.', ['are watching', 'is watching', 'watch'], 0, 'Они сейчас смотрят телевизор.'],
        ['What ___ you doing?', ['are', 'is', 'do'], 0, 'Что ты делаешь?'],
        ['He isn’t ___ now.', ['sleeping', 'sleep', 'sleeps'], 0, 'Он сейчас не спит.'],
        ['We ___ shopping now.', ['are going', 'go', 'goes'], 0, 'Мы сейчас идём за покупками.'],
        ['Listen! The baby ___.', ['is crying', 'cries', 'are crying'], 0, 'Слушай! Малыш плачет.'],
        ['She is ___ in the sea.', ['swimming', 'swiming', 'swims'], 0, 'Она плавает в море.'],
        ['___ your dad working now?', ['Is', 'Are', 'Does'], 0, 'Твой папа сейчас работает?'],
        ['I am ___ a cake for Mum.', ['making', 'makeing', 'make'], 0, 'Я готовлю торт для мамы.'],
      ],
    },
  },
  {
    id: 'directions',
    title: 'Around town',
    ru: 'По городу',
    level: 'A1',
    grades: [5, 7],
    icon: '🗺️',
    words: [
      ['street', 'улица'],
      ['square', 'площадь'],
      ['park', 'парк', '🌳'],
      ['bank', 'банк', '🏦'],
      ['post office', 'почта', '🏤'],
      ['hospital', 'больница', '🏥'],
      ['chemist’s', 'аптека', '💊'],
      ['supermarket', 'супермаркет', '🛒'],
      ['museum', 'музей', '🏛️'],
      ['cinema', 'кинотеатр', '🎬'],
      ['bridge', 'мост', '🌉'],
      ['bus stop', 'автобусная остановка', '🚏'],
      ['station', 'вокзал, станция', '🚉'],
      ['traffic lights', 'светофор', '🚦'],
      ['corner', 'угол'],
      ['opposite', 'напротив'],
      ['turn left', 'повернуть налево', '⬅️'],
      ['turn right', 'повернуть направо', '➡️'],
      ['go straight on', 'идти прямо', '⬆️'],
      ['cross', 'переходить (улицу)'],
    ],
    phrases: [
      ['Excuse me, where is the station?', 'Извините, где вокзал?'],
      ['Go straight on and turn left.', 'Идите прямо и поверните налево.'],
      ['It is opposite the bank.', 'Это напротив банка.'],
      ['Cross the street at the traffic lights.', 'Переходите улицу на светофоре.'],
      ['The museum is on the corner.', 'Музей на углу.'],
      ['Take the second street on the right.', 'Поверните на вторую улицу направо.'],
      ['Is it far from here?', 'Это далеко отсюда?'],
      ['It is about five minutes on foot.', 'Минут пять пешком.'],
      ['Don’t cross the road here!', 'Не переходи дорогу здесь!'],
      ['Let’s meet at the bus stop.', 'Давай встретимся на остановке.'],
    ],
    grammar: {
      title: 'Повелительное наклонение и Let’s',
      rule: ['Просьба или команда — глагол без to и без подлежащего: Turn left. Open the door.', 'Не делай: Don’t + глагол: Don’t run!', 'Давай(те): Let’s + глагол: Let’s go to the park.'],
      gaps: [
        ['___ left at the bank.', ['Turn', 'Turns', 'Turning'], 0, 'Поверните налево у банка.'],
        ['___ cross the road here!', ['Don’t', 'Not', 'No'], 0, 'Не переходи дорогу здесь!'],
        ['___ go to the cinema.', ['Let’s', 'Lets', 'Let'], 0, 'Давай пойдём в кино.'],
        ['Please ___ the window.', ['close', 'closes', 'to close'], 0, 'Закрой, пожалуйста, окно.'],
        ['Don’t ___ in the museum.', ['run', 'running', 'runs'], 0, 'Не бегай в музее.'],
        ['Let’s ___ at the station.', ['meet', 'to meet', 'meeting'], 0, 'Давай встретимся на вокзале.'],
        ['The bank is ___ the post office. (напротив)', ['opposite', 'opposite of', 'front'], 0, 'Банк напротив почты.'],
        ['The cafe is ___ the corner.', ['on', 'in', 'at the'], 0, 'Кафе на углу.'],
        ['___ straight on to the square.', ['Go', 'Goes', 'Going'], 0, 'Идите прямо до площади.'],
        ['Be careful! ___ touch it!', ['Don’t', 'Doesn’t', 'Not'], 0, 'Осторожно! Не трогай!'],
      ],
    },
  },
  {
    id: 'weather',
    title: 'Weather and seasons',
    ru: 'Погода и времена года',
    level: 'A1',
    grades: [5, 7],
    icon: '🌦️',
    words: [
      ['sunny', 'солнечно', '☀️'],
      ['cloudy', 'облачно', '☁️'],
      ['rainy', 'дождливо', '🌧️'],
      ['snowy', 'снежно', '❄️'],
      ['windy', 'ветрено', '💨'],
      ['foggy', 'туманно', '🌫️'],
      ['hot', 'жарко', '🥵'],
      ['warm', 'тепло'],
      ['cold', 'холодно', '🥶'],
      ['storm', 'гроза, буря', '⛈️'],
      ['rainbow', 'радуга', '🌈'],
      ['spring', 'весна', '🌷'],
      ['summer', 'лето', '🏖️'],
      ['autumn', 'осень', '🍂'],
      ['winter', 'зима', '⛄'],
      ['January', 'январь'],
      ['April', 'апрель'],
      ['July', 'июль'],
      ['October', 'октябрь'],
      ['temperature', 'температура', '🌡️'],
    ],
    phrases: [
      ['What is the weather like today?', 'Какая сегодня погода?'],
      ['It is raining now.', 'Сейчас идёт дождь.'],
      ['It often rains in autumn.', 'Осенью часто идут дожди.'],
      ['It snows a lot in winter.', 'Зимой много снега.'],
      ['Look! There is a rainbow!', 'Смотри! Радуга!'],
      ['It is minus ten today.', 'Сегодня минус десять.'],
      ['My birthday is in July.', 'Мой день рождения в июле.'],
      ['We usually go to the sea in summer.', 'Летом мы обычно ездим на море.'],
      ['This week we are staying at home.', 'На этой неделе мы сидим дома.'],
      ['Take an umbrella, it is cloudy.', 'Возьми зонт, облачно.'],
    ],
    grammar: {
      title: 'Present Simple или Present Continuous',
      rule: ['Present Simple — обычно, всегда, часто: It often rains in autumn.', 'Present Continuous — прямо сейчас или в эти дни: It is raining now.', 'Глаголы чувств и знаний (like, love, know, want) обычно без -ing: I want ice cream (не I am wanting).'],
      gaps: [
        ['It ___ a lot in winter.', ['snows', 'is snowing', 'snow'], 0, 'Зимой много снега.'],
        ['Look outside! It ___.', ['is snowing', 'snows', 'snow'], 0, 'Посмотри! Идёт снег.'],
        ['We usually ___ to the sea in summer.', ['go', 'are going', 'goes'], 0, 'Летом мы обычно ездим на море.'],
        ['I ___ a jumper now because it is cold.', ['am wearing', 'wear', 'wears'], 0, 'Сейчас я в свитере, потому что холодно.'],
        ['She ___ hot weather.', ['likes', 'is liking', 'like'], 0, 'Она любит жару.'],
        ['What ___ you doing at the moment?', ['are', 'do', 'is'], 0, 'Что ты сейчас делаешь?'],
        ['It never ___ in the desert.', ['rains', 'is raining', 'rain'], 0, 'В пустыне никогда не бывает дождя.'],
        ['I ___ the answer.', ['know', 'am knowing', 'knows'], 0, 'Я знаю ответ.'],
        ['Listen! The birds ___.', ['are singing', 'sing', 'sings'], 0, 'Слушай! Птицы поют.'],
        ['My birthday is ___ April.', ['in', 'on', 'at'], 0, 'Мой день рождения в апреле.'],
      ],
    },
  },
  {
    id: 'wild',
    title: 'Wild world',
    ru: 'Дикая природа',
    level: 'A1',
    grades: [5, 7],
    icon: '🦁',
    words: [
      ['wolf', 'волк', '🐺'],
      ['crocodile', 'крокодил', '🐊'],
      ['whale', 'кит', '🐋'],
      ['dolphin', 'дельфин', '🐬'],
      ['shark', 'акула', '🦈'],
      ['eagle', 'орёл', '🦅'],
      ['owl', 'сова', '🦉'],
      ['penguin', 'пингвин', '🐧'],
      ['camel', 'верблюд', '🐫'],
      ['kangaroo', 'кенгуру', '🦘'],
      ['jungle', 'джунгли', '🌴'],
      ['desert', 'пустыня', '🏜️'],
      ['ocean', 'океан', '🌊'],
      ['mountain', 'гора', '⛰️'],
      ['forest', 'лес', '🌲'],
      ['fast', 'быстрый'],
      ['slow', 'медленный', '🐢'],
      ['dangerous', 'опасный', '⚠️'],
      ['heavy', 'тяжёлый'],
      ['clever', 'умный'],
    ],
    phrases: [
      ['A whale is bigger than a dolphin.', 'Кит больше дельфина.'],
      ['The cheetah is the fastest animal.', 'Гепард — самое быстрое животное.'],
      ['Sharks are more dangerous than dolphins.', 'Акулы опаснее дельфинов.'],
      ['Penguins can’t fly.', 'Пингвины не умеют летать.'],
      ['Camels live in the desert.', 'Верблюды живут в пустыне.'],
      ['Owls sleep in the day.', 'Совы спят днём.'],
      ['This is the best film about animals.', 'Это лучший фильм о животных.'],
      ['My dog is cleverer than my cat.', 'Моя собака умнее моей кошки.'],
      ['Which animal is the heaviest?', 'Какое животное самое тяжёлое?'],
      ['Turtles are slower than rabbits.', 'Черепахи медленнее кроликов.'],
    ],
    grammar: {
      title: 'Сравнение: bigger, the biggest',
      rule: ['Короткие слова: fast → faster → the fastest; big → bigger → the biggest; heavy → heavier → the heaviest.', 'Длинные слова: dangerous → more dangerous → the most dangerous.', 'Особые: good → better → the best; bad → worse → the worst. Сравниваем через than: bigger than a cat.'],
      gaps: [
        ['A whale is ___ than a dolphin.', ['bigger', 'biger', 'more big'], 0, 'Кит больше дельфина.'],
        ['The cheetah is ___ animal.', ['the fastest', 'the most fast', 'fastest'], 0, 'Гепард — самое быстрое животное.'],
        ['Sharks are ___ than dolphins.', ['more dangerous', 'dangerouser', 'most dangerous'], 0, 'Акулы опаснее дельфинов.'],
        ['An elephant is ___ than a horse.', ['heavier', 'heavyer', 'more heavy'], 0, 'Слон тяжелее лошади.'],
        ['This is ___ book in the library!', ['the best', 'the goodest', 'the better'], 0, 'Это лучшая книга в библиотеке!'],
        ['Today the weather is ___ than yesterday.', ['worse', 'badder', 'more bad'], 0, 'Сегодня погода хуже, чем вчера.'],
        ['A turtle is slower ___ a rabbit.', ['than', 'that', 'then'], 0, 'Черепаха медленнее кролика.'],
        ['Everest is ___ mountain in the world.', ['the highest', 'the most high', 'higher'], 0, 'Эверест — самая высокая гора в мире.'],
        ['My cat is ___ than my dog.', ['cleverer', 'more clever than', 'cleverest'], 0, 'Моя кошка умнее собаки.'],
        ['The Pacific is ___ ocean.', ['the largest', 'the larger', 'largest'], 0, 'Тихий — крупнейший океан.'],
      ],
    },
  },
];
