import type { Unit } from '../types.js';

// A2: was/were, Past Simple, Past Continuous, be going to, will, should/must,
// превосходная степень и too/enough, наречия, have to, глагол + -ing / to.
export const A2: Unit[] = [
  {
    id: 'yesterday',
    title: 'Where were you?',
    ru: 'Где ты был?',
    level: 'A2',
    grades: [6, 8],
    icon: '🕰️',
    words: [
      ['yesterday', 'вчера'],
      ['last night', 'вчера вечером'],
      ['last week', 'на прошлой неделе'],
      ['ago', 'назад'],
      ['born', 'рождённый'],
      ['at home', 'дома'],
      ['at school', 'в школе'],
      ['at the party', 'на вечеринке', '🎉'],
      ['on holiday', 'в отпуске, на каникулах', '🏖️'],
      ['tired', 'уставший', '😴'],
      ['bored', 'скучающий'],
      ['excited', 'взволнованный', '🤩'],
      ['angry', 'сердитый', '😠'],
      ['scared', 'испуганный', '😱'],
      ['hungry', 'голодный'],
      ['thirsty', 'испытывающий жажду'],
      ['ill', 'больной', '🤒'],
      ['late', 'опоздавший, поздно'],
      ['early', 'рано'],
      ['busy', 'занятой'],
    ],
    phrases: [
      ['Where were you yesterday?', 'Где ты был вчера?'],
      ['I was at home.', 'Я был дома.'],
      ['We were very tired.', 'Мы очень устали.'],
      ['Was it cold last night?', 'Вчера вечером было холодно?'],
      ['No, it wasn’t.', 'Нет.'],
      ['I was born in 2012.', 'Я родился в 2012 году.'],
      ['They weren’t at school last week.', 'На прошлой неделе их не было в школе.'],
      ['The party was great!', 'Вечеринка была отличной!'],
      ['Who was with you?', 'Кто был с тобой?'],
      ['Two years ago I was in London.', 'Два года назад я был в Лондоне.'],
    ],
    grammar: {
      title: 'was / were',
      rule: ['Прошлое глагола to be: I / he / she / it was; we / you / they were.', 'Отрицание: wasn’t, weren’t. Вопрос: Were you at home? Was she ill?', 'Подсказки: yesterday, last week, two days ago, in 2015.'],
      gaps: [
        ['I ___ at home yesterday.', ['was', 'were', 'am'], 0, 'Вчера я был дома.'],
        ['They ___ at the party.', ['were', 'was', 'are'], 0, 'Они были на вечеринке.'],
        ['___ you tired last night?', ['Were', 'Was', 'Did'], 0, 'Ты вчера устал?'],
        ['She ___ at school last week, she was ill.', ['wasn’t', 'weren’t', 'didn’t'], 0, 'Её не было в школе: она болела.'],
        ['Where ___ your parents yesterday?', ['were', 'was', 'did'], 0, 'Где вчера были твои родители?'],
        ['It ___ very cold last winter.', ['was', 'were', 'is'], 0, 'Прошлой зимой было очень холодно.'],
        ['I was born ___ 2012.', ['in', 'on', 'at'], 0, 'Я родился в 2012 году.'],
        ['We ___ late for the lesson.', ['were', 'was', 'did'], 0, 'Мы опоздали на урок.'],
        ['Was the film good? — Yes, it ___.', ['was', 'were', 'did'], 0, 'Да.'],
        ['Three days ___ I was in Moscow.', ['ago', 'before ago', 'last'], 0, 'Три дня назад я был в Москве.'],
      ],
    },
  },
  {
    id: 'weekend',
    title: 'Last weekend',
    ru: 'Прошлые выходные',
    level: 'A2',
    grades: [6, 8],
    icon: '📸',
    words: [
      ['went', 'ходил, ездил (go)'],
      ['saw', 'видел (see)'],
      ['bought', 'купил (buy)'],
      ['ate', 'ел (eat)'],
      ['drank', 'пил (drink)'],
      ['made', 'сделал (make)'],
      ['wrote', 'написал (write)'],
      ['came', 'пришёл (come)'],
      ['took', 'взял (take)'],
      ['gave', 'дал (give)'],
      ['met', 'встретил (meet)'],
      ['found', 'нашёл (find)'],
      ['lost', 'потерял (lose)'],
      ['won', 'выиграл (win)'],
      ['left', 'ушёл, уехал (leave)'],
      ['told', 'рассказал (tell)'],
      ['visited', 'навестил'],
      ['played', 'играл'],
      ['stayed', 'остался'],
      ['cooked', 'приготовил'],
    ],
    phrases: [
      ['I went to the cinema yesterday.', 'Вчера я ходил в кино.'],
      ['We visited our grandmother last Sunday.', 'В прошлое воскресенье мы навестили бабушку.'],
      ['She bought a new phone.', 'Она купила новый телефон.'],
      ['Our team won the match!', 'Наша команда выиграла матч!'],
      ['I lost my keys.', 'Я потерял ключи.'],
      ['They played football in the park.', 'Они играли в футбол в парке.'],
      ['My mum cooked a big dinner.', 'Мама приготовила большой ужин.'],
      ['I met my friend at the station.', 'Я встретил друга на вокзале.'],
      ['He told me a funny story.', 'Он рассказал мне смешную историю.'],
      ['We stayed at home because it rained.', 'Мы остались дома, потому что шёл дождь.'],
    ],
    grammar: {
      title: 'Past Simple: правильные и неправильные глаголы',
      rule: ['Правильные + ed: play → played, visit → visited, stop → stopped, study → studied.', 'Неправильные — вторая форма из таблицы: go → went, see → saw, buy → bought, eat → ate.', 'Подсказки: yesterday, last…, …ago, in 2019, when I was five.'],
      gaps: [
        ['Yesterday I ___ to the park.', ['went', 'go', 'goed'], 0, 'Вчера я ходил в парк.'],
        ['She ___ a cake last Sunday.', ['made', 'maked', 'make'], 0, 'В прошлое воскресенье она испекла торт.'],
        ['We ___ our grandparents.', ['visited', 'visit', 'visitted'], 0, 'Мы навестили бабушку и дедушку.'],
        ['I ___ a letter to my friend.', ['wrote', 'writed', 'write'], 0, 'Я написал письмо другу.'],
        ['They ___ the match 3:1.', ['won', 'winned', 'win'], 0, 'Они выиграли матч 3:1.'],
        ['He ___ his homework in the evening.', ['did', 'done', 'doed'], 0, 'Он сделал уроки вечером.'],
        ['The bus ___ at the corner.', ['stopped', 'stoped', 'stops'], 0, 'Автобус остановился на углу.'],
        ['We ___ pizza for dinner.', ['ate', 'eated', 'eat'], 0, 'На ужин мы ели пиццу.'],
        ['She ___ English for two hours.', ['studied', 'studyed', 'studies'], 0, 'Она два часа занималась английским.'],
        ['I ___ a strange noise last night.', ['heard', 'heared', 'hear'], 0, 'Вчера ночью я услышал странный шум.'],
      ],
    },
  },
  {
    id: 'stories',
    title: 'Stories',
    ru: 'Истории и приключения',
    level: 'A2',
    grades: [7, 8],
    icon: '📖',
    words: [
      ['suddenly', 'вдруг'],
      ['while', 'пока, в то время как'],
      ['when', 'когда'],
      ['then', 'затем'],
      ['finally', 'наконец'],
      ['happen', 'случаться'],
      ['fall', 'падать'],
      ['break', 'ломать'],
      ['hear', 'слышать', '👂'],
      ['shout', 'кричать', '📢'],
      ['ring', 'звонить', '🔔'],
      ['knock', 'стучать', '🚪'],
      ['dark', 'тёмный', '🌑'],
      ['noise', 'шум'],
      ['ghost', 'привидение', '👻'],
      ['adventure', 'приключение', '🗺️'],
      ['island', 'остров', '🏝️'],
      ['treasure', 'сокровище', '💰'],
      ['accident', 'несчастный случай, авария'],
      ['lucky', 'везучий', '🍀'],
    ],
    phrases: [
      ['What were you doing at eight o’clock?', 'Что ты делал в восемь часов?'],
      ['I was watching a film.', 'Я смотрел фильм.'],
      ['While I was reading, the phone rang.', 'Пока я читал, зазвонил телефон.'],
      ['Suddenly we heard a noise.', 'Вдруг мы услышали шум.'],
      ['It was dark and it was raining.', 'Было темно, и шёл дождь.'],
      ['Did you see the ghost?', 'Ты видел привидение?'],
      ['No, I didn’t see anything.', 'Нет, я ничего не видел.'],
      ['He fell and broke his arm.', 'Он упал и сломал руку.'],
      ['What happened next?', 'Что случилось потом?'],
      ['Finally they found the treasure.', 'Наконец они нашли сокровище.'],
    ],
    grammar: {
      title: 'Past Simple: вопросы и отрицания; Past Continuous',
      rule: ['Вопрос и отрицание — через did / didn’t + первая форма: Did you see it? I didn’t go.', 'Past Continuous — процесс в прошлом: was / were + -ing: I was reading at 8.', 'Процесс прервало действие: While I was reading, the phone rang.'],
      gaps: [
        ['___ you see the film yesterday?', ['Did', 'Do', 'Were'], 0, 'Ты вчера смотрел фильм?'],
        ['I didn’t ___ to school yesterday.', ['go', 'went', 'goes'], 0, 'Вчера я не ходил в школу.'],
        ['Where did you ___ your holidays?', ['spend', 'spent', 'spends'], 0, 'Где ты провёл каникулы?'],
        ['At eight o’clock I ___ dinner.', ['was having', 'had', 'were having'], 0, 'В восемь я ужинал.'],
        ['They ___ football when it started to rain.', ['were playing', 'was playing', 'played'], 0, 'Они играли в футбол, когда начался дождь.'],
        ['While I was walking home, I ___ my friend.', ['met', 'was meeting', 'meet'], 0, 'Пока я шёл домой, я встретил друга.'],
        ['What ___ you doing at 10 p.m.?', ['were', 'did', 'was'], 0, 'Что ты делал в 10 вечера?'],
        ['She ___ hear the phone.', ['didn’t', 'wasn’t', 'don’t'], 0, 'Она не услышала телефон.'],
        ['What ___ next?', ['happened', 'happen', 'did happen'], 0, 'Что случилось дальше?'],
        ['The sun ___ and the birds were singing.', ['was shining', 'shone was', 'were shining'], 0, 'Светило солнце, пели птицы.'],
      ],
    },
  },
  {
    id: 'travel',
    title: 'Holidays and travel',
    ru: 'Путешествия',
    level: 'A2',
    grades: [6, 9],
    icon: '✈️',
    words: [
      ['travel', 'путешествовать', '✈️'],
      ['trip', 'поездка'],
      ['journey', 'путешествие (дорога)'],
      ['ticket', 'билет', '🎫'],
      ['passport', 'паспорт', '🛂'],
      ['suitcase', 'чемодан', '🧳'],
      ['airport', 'аэропорт', '🛫'],
      ['plane', 'самолёт', '✈️'],
      ['train', 'поезд', '🚆'],
      ['ship', 'корабль', '🚢'],
      ['hotel', 'гостиница', '🏨'],
      ['beach', 'пляж', '🏖️'],
      ['tent', 'палатка', '⛺'],
      ['map', 'карта', '🗺️'],
      ['abroad', 'за границей'],
      ['sightseeing', 'осмотр достопримечательностей'],
      ['souvenir', 'сувенир', '🎁'],
      ['book', 'бронировать'],
      ['pack', 'собирать вещи'],
      ['arrive', 'прибывать'],
    ],
    phrases: [
      ['We are going to travel to the sea.', 'Мы собираемся поехать на море.'],
      ['I am going to visit my grandparents.', 'Я собираюсь навестить бабушку и дедушку.'],
      ['What are you going to do in summer?', 'Что ты собираешься делать летом?'],
      ['She isn’t going to stay at a hotel.', 'Она не собирается жить в гостинице.'],
      ['Don’t forget your passport!', 'Не забудь паспорт!'],
      ['Our plane leaves at six.', 'Наш самолёт вылетает в шесть.'],
      ['Look at those clouds — it’s going to rain.', 'Посмотри на тучи — сейчас пойдёт дождь.'],
      ['I’m packing my suitcase.', 'Я собираю чемодан.'],
      ['We booked the tickets online.', 'Мы забронировали билеты онлайн.'],
      ['They are going to go sightseeing.', 'Они собираются осматривать достопримечательности.'],
    ],
    grammar: {
      title: 'be going to — планы и «вот-вот»',
      rule: ['Планы и намерения: am / is / are going to + глагол: I am going to travel.', 'Вот-вот случится (видно по признакам): Look at the clouds — it’s going to rain.', 'Отрицание: I’m not going to… Вопрос: Are you going to…?'],
      gaps: [
        ['I ___ going to visit Paris.', ['am', 'is', 'are'], 0, 'Я собираюсь посетить Париж.'],
        ['They are going ___ a tent.', ['to buy', 'buy', 'buying'], 0, 'Они собираются купить палатку.'],
        ['She ___ going to stay at home.', ['isn’t', 'aren’t', 'don’t'], 0, 'Она не собирается сидеть дома.'],
        ['___ you going to travel abroad?', ['Are', 'Do', 'Is'], 0, 'Ты собираешься за границу?'],
        ['Look at the sky! It’s going ___ rain.', ['to', 'for', '—'], 0, 'Посмотри на небо! Сейчас пойдёт дождь.'],
        ['What ___ he going to do?', ['is', 'are', 'does'], 0, 'Что он собирается делать?'],
        ['We are going to ___ to the beach.', ['go', 'going', 'goes'], 0, 'Мы собираемся на пляж.'],
        ['I’m going to ___ my suitcase tonight.', ['pack', 'packing', 'packed'], 0, 'Сегодня вечером я соберу чемодан.'],
        ['My parents ___ going to book a hotel.', ['are', 'is', 'am'], 0, 'Мои родители собираются забронировать отель.'],
        ['He’s going to miss the train! He ___ late.', ['is', 'are', 'does'], 0, 'Он опоздает на поезд! Он опаздывает.'],
      ],
    },
  },
  {
    id: 'future',
    title: 'The future',
    ru: 'Будущее',
    level: 'A2',
    grades: [7, 9],
    icon: '🚀',
    words: [
      ['future', 'будущее', '🔮'],
      ['robot', 'робот', '🤖'],
      ['space', 'космос', '🌌'],
      ['planet', 'планета', '🪐'],
      ['rocket', 'ракета', '🚀'],
      ['invent', 'изобретать'],
      ['technology', 'технологии'],
      ['probably', 'вероятно'],
      ['maybe', 'может быть'],
      ['definitely', 'точно, определённо'],
      ['think', 'думать'],
      ['hope', 'надеяться'],
      ['promise', 'обещать'],
      ['decide', 'решать'],
      ['help', 'помогать'],
      ['tomorrow', 'завтра'],
      ['next year', 'в следующем году'],
      ['soon', 'скоро'],
      ['one day', 'однажды'],
      ['world', 'мир', '🌍'],
    ],
    phrases: [
      ['I think robots will do our homework.', 'Думаю, роботы будут делать за нас уроки.'],
      ['People will live on Mars one day.', 'Однажды люди будут жить на Марсе.'],
      ['It will be sunny tomorrow.', 'Завтра будет солнечно.'],
      ['I will help you.', 'Я тебе помогу.'],
      ['I promise I won’t be late.', 'Обещаю, я не опоздаю.'],
      ['Will you come to my party?', 'Ты придёшь ко мне на праздник?'],
      ['Maybe we will travel to space.', 'Может быть, мы полетим в космос.'],
      ['The phone is ringing. I’ll answer it.', 'Звонит телефон. Я отвечу.'],
      ['Cars will probably fly.', 'Машины, вероятно, будут летать.'],
      ['I hope you will win.', 'Надеюсь, ты победишь.'],
    ],
    grammar: {
      title: 'will / won’t',
      rule: ['Прогнозы и мнения: I think it will rain. People will live on Mars.', 'Решение прямо сейчас и обещания: I’ll answer it. I promise I’ll help.', 'will + глагол без to. Отрицание: won’t (= will not). Вопрос: Will you…?'],
      gaps: [
        ['I think it ___ rain tomorrow.', ['will', 'is', 'does'], 0, 'Думаю, завтра будет дождь.'],
        ['People ___ live on Mars one day.', ['will', 'are', 'do'], 0, 'Однажды люди будут жить на Марсе.'],
        ['I promise I ___ be late again.', ['won’t', 'don’t', 'am not'], 0, 'Обещаю, больше не опоздаю.'],
        ['___ you help me, please?', ['Will', 'Are', 'Do'], 0, 'Поможешь мне?'],
        ['Robots will ___ our homework.', ['do', 'to do', 'doing'], 0, 'Роботы будут делать наши уроки.'],
        ['The phone is ringing. I ___ answer it.', ['’ll', '’m going', '’d'], 0, 'Звонит телефон. Я отвечу.'],
        ['Maybe she ___ come to the party.', ['will', 'is', 'won'], 0, 'Может, она придёт на праздник.'],
        ['Cars will probably ___.', ['fly', 'flies', 'flying'], 0, 'Машины, вероятно, будут летать.'],
        ['I’m sure you ___ win!', ['will', 'are', 'would'], 0, 'Уверен, ты победишь!'],
        ['It’s cold. I ___ close the window.', ['’ll', '’m', '’s'], 0, 'Холодно. Я закрою окно.'],
      ],
    },
  },
  {
    id: 'health',
    title: 'Health',
    ru: 'Здоровье',
    level: 'A2',
    grades: [7, 9],
    icon: '🩺',
    words: [
      ['headache', 'головная боль', '🤕'],
      ['toothache', 'зубная боль', '🦷'],
      ['stomachache', 'боль в животе'],
      ['cold', 'простуда', '🤧'],
      ['cough', 'кашель'],
      ['fever', 'температура (жар)', '🌡️'],
      ['sore throat', 'больное горло'],
      ['medicine', 'лекарство', '💊'],
      ['dentist', 'стоматолог'],
      ['nurse', 'медсестра', '🧑‍⚕️'],
      ['rest', 'отдыхать'],
      ['healthy', 'здоровый', '🥗'],
      ['unhealthy', 'вредный для здоровья'],
      ['exercise', 'упражнения, зарядка', '🏋️'],
      ['vegetables', 'овощи', '🥦'],
      ['fast food', 'фастфуд', '🍔'],
      ['sleep', 'сон', '😴'],
      ['hurt', 'болеть, ушибить'],
      ['feel', 'чувствовать'],
      ['better', 'лучше'],
    ],
    phrases: [
      ['What’s the matter?', 'Что случилось?'],
      ['I have got a headache.', 'У меня болит голова.'],
      ['You should go to bed.', 'Тебе стоит лечь в постель.'],
      ['You shouldn’t eat so much fast food.', 'Тебе не стоит есть столько фастфуда.'],
      ['You must take this medicine.', 'Ты должен принять это лекарство.'],
      ['You mustn’t swim after lunch.', 'Нельзя плавать сразу после обеда.'],
      ['I feel much better today.', 'Сегодня мне гораздо лучше.'],
      ['Drink a lot of water.', 'Пей много воды.'],
      ['My leg hurts.', 'У меня болит нога.'],
      ['Get well soon!', 'Выздоравливай!'],
    ],
    grammar: {
      title: 'should / shouldn’t, must / mustn’t',
      rule: ['should — совет: You should rest. shouldn’t — не стоит: You shouldn’t eat sweets.', 'must — обязательно, правило: You must take the medicine.', 'mustn’t — нельзя, запрещено: You mustn’t run in the corridor.', 'После should и must — глагол без to.'],
      gaps: [
        ['You have a cold. You ___ stay in bed.', ['should', 'shouldn’t', 'mustn’t'], 0, 'У тебя простуда. Тебе стоит полежать.'],
        ['You ___ eat so many sweets.', ['shouldn’t', 'should', 'must'], 0, 'Тебе не стоит есть столько сладкого.'],
        ['You ___ use your phone in the exam!', ['mustn’t', 'must', 'should'], 0, 'На экзамене пользоваться телефоном нельзя!'],
        ['You must ___ this medicine twice a day.', ['take', 'to take', 'taking'], 0, 'Нужно принимать это лекарство дважды в день.'],
        ['___ I go to the doctor?', ['Should', 'Must I to', 'Do should'], 0, 'Мне стоит пойти к врачу?'],
        ['Drivers ___ stop at a red light.', ['must', 'mustn’t', 'shouldn’t'], 0, 'Водители должны останавливаться на красный.'],
        ['You should ___ more vegetables.', ['eat', 'to eat', 'eating'], 0, 'Тебе стоит есть больше овощей.'],
        ['What’s the ___? — I have a toothache.', ['matter', 'problem of', 'wrong'], 0, 'Что случилось? — Болит зуб.'],
        ['I ___ much better today, thank you.', ['feel', 'am feel', 'feels'], 0, 'Сегодня мне гораздо лучше, спасибо.'],
        ['You ___ shout in the library.', ['mustn’t', 'must', 'should'], 0, 'В библиотеке нельзя кричать.'],
      ],
    },
  },
  {
    id: 'sport',
    title: 'Sport',
    ru: 'Спорт',
    level: 'A2',
    grades: [6, 9],
    icon: '🏆',
    words: [
      ['basketball', 'баскетбол', '🏀'],
      ['volleyball', 'волейбол', '🏐'],
      ['tennis', 'теннис', '🎾'],
      ['hockey', 'хоккей', '🏒'],
      ['boxing', 'бокс', '🥊'],
      ['skiing', 'лыжи (вид спорта)', '⛷️'],
      ['skating', 'катание на коньках', '⛸️'],
      ['running', 'бег', '🏃'],
      ['team', 'команда'],
      ['player', 'игрок'],
      ['coach', 'тренер'],
      ['match', 'матч'],
      ['score', 'счёт'],
      ['goal', 'гол', '🥅'],
      ['win', 'побеждать', '🏆'],
      ['lose', 'проигрывать'],
      ['champion', 'чемпион', '🥇'],
      ['stadium', 'стадион', '🏟️'],
      ['strong', 'сильный', '💪'],
      ['enough', 'достаточно'],
    ],
    phrases: [
      ['He is the best player in our team.', 'Он лучший игрок нашей команды.'],
      ['It was the most exciting match of the year.', 'Это был самый захватывающий матч года.'],
      ['Our team won two goals to one.', 'Наша команда выиграла со счётом 2:1.'],
      ['I am not tall enough for basketball.', 'Я недостаточно высокий для баскетбола.'],
      ['The water is too cold to swim.', 'Вода слишком холодная, чтобы плавать.'],
      ['Who is your favourite player?', 'Кто твой любимый игрок?'],
      ['Our coach is very strict.', 'Наш тренер очень строгий.'],
      ['We train three times a week.', 'Мы тренируемся три раза в неделю.'],
      ['She became champion at fifteen.', 'Она стала чемпионкой в пятнадцать.'],
      ['Let’s go to the stadium!', 'Пошли на стадион!'],
    ],
    grammar: {
      title: 'Превосходная степень, too и enough',
      rule: ['Самый: the + -est (the fastest) или the most + длинное слово (the most exciting). Особые: the best, the worst.', 'too + прилагательное — слишком: too cold.', 'прилагательное + enough — достаточно: tall enough. Не достаточно: not strong enough.'],
      gaps: [
        ['He is ___ player in the team.', ['the best', 'the goodest', 'better'], 0, 'Он лучший игрок команды.'],
        ['It was ___ match of the year.', ['the most exciting', 'the excitingest', 'more exciting'], 0, 'Это был самый захватывающий матч года.'],
        ['The water is ___ cold to swim.', ['too', 'enough', 'very much'], 0, 'Вода слишком холодная, чтобы плавать.'],
        ['I am not tall ___ for basketball.', ['enough', 'too', 'very'], 0, 'Я недостаточно высокий для баскетбола.'],
        ['This is ___ team in the city.', ['the worst', 'the baddest', 'the most bad'], 0, 'Это худшая команда города.'],
        ['Ivan is ___ boy in our class.', ['the tallest', 'the most tall', 'taller'], 0, 'Иван — самый высокий мальчик в классе.'],
        ['The box is ___ heavy for me.', ['too', 'enough', 'so much'], 0, 'Коробка слишком тяжёлая для меня.'],
        ['Are you strong ___ to lift it?', ['enough', 'too', 'very'], 0, 'Ты достаточно сильный, чтобы поднять её?'],
        ['Hockey is ___ popular sport in Canada.', ['the most', 'the more', 'most the'], 0, 'Хоккей — самый популярный спорт в Канаде.'],
        ['Who ___ the match yesterday?', ['won', 'win', 'winned'], 0, 'Кто вчера выиграл матч?'],
      ],
    },
  },
  {
    id: 'feelings',
    title: 'Feelings and character',
    ru: 'Чувства и характер',
    level: 'A2',
    grades: [7, 9],
    icon: '🎭',
    words: [
      ['friendly', 'дружелюбный'],
      ['shy', 'застенчивый'],
      ['brave', 'смелый', '🦸'],
      ['lazy', 'ленивый', '🦥'],
      ['hard-working', 'трудолюбивый'],
      ['polite', 'вежливый'],
      ['rude', 'грубый'],
      ['honest', 'честный'],
      ['generous', 'щедрый'],
      ['selfish', 'эгоистичный'],
      ['calm', 'спокойный', '😌'],
      ['nervous', 'нервный'],
      ['proud', 'гордый'],
      ['surprised', 'удивлённый', '😮'],
      ['interested', 'заинтересованный'],
      ['interesting', 'интересный'],
      ['boring', 'скучный'],
      ['carefully', 'осторожно, внимательно'],
      ['quickly', 'быстро'],
      ['well', 'хорошо (как?)'],
    ],
    phrases: [
      ['She is very friendly and polite.', 'Она очень дружелюбная и вежливая.'],
      ['He speaks English well.', 'Он хорошо говорит по-английски.'],
      ['Please read the text carefully.', 'Пожалуйста, прочитай текст внимательно.'],
      ['I was bored at the lesson.', 'Мне было скучно на уроке.'],
      ['The lesson was boring.', 'Урок был скучным.'],
      ['I am interested in history.', 'Я интересуюсь историей.'],
      ['My brother is a bit lazy.', 'Мой брат немного ленивый.'],
      ['She ran quickly to the bus.', 'Она быстро побежала к автобусу.'],
      ['I feel nervous before tests.', 'Я нервничаю перед контрольными.'],
      ['We were surprised by the news.', 'Нас удивила новость.'],
    ],
    grammar: {
      title: 'Наречия -ly и прилагательные -ed / -ing',
      rule: ['Какой? — прилагательное: a quick runner. Как? — наречие: He runs quickly.', 'Особые: good → well, fast → fast, hard → hard.', '-ed — что я чувствую: I’m bored. -ing — какое что-то: The film is boring.'],
      gaps: [
        ['He speaks English very ___.', ['well', 'good', 'goodly'], 0, 'Он очень хорошо говорит по-английски.'],
        ['Read the instructions ___.', ['carefully', 'careful', 'carefuly'], 0, 'Прочитай инструкцию внимательно.'],
        ['She is a ___ driver.', ['careful', 'carefully', 'care'], 0, 'Она аккуратный водитель.'],
        ['The film was really ___.', ['boring', 'bored', 'bore'], 0, 'Фильм был очень скучным.'],
        ['I was ___ at the lesson.', ['bored', 'boring', 'bore'], 0, 'Мне было скучно на уроке.'],
        ['I’m ___ in space.', ['interested', 'interesting', 'interest'], 0, 'Я интересуюсь космосом.'],
        ['He ran ___ to catch the bus.', ['quickly', 'quick', 'quicker'], 0, 'Он быстро побежал на автобус.'],
        ['The news was very ___.', ['surprising', 'surprised', 'surprise'], 0, 'Новость была очень неожиданной.'],
        ['She works very ___.', ['hard', 'hardly', 'hardy'], 0, 'Она очень усердно работает.'],
        ['They answered the question ___.', ['correctly', 'correct', 'corrected'], 0, 'Они правильно ответили на вопрос.'],
      ],
    },
  },
  {
    id: 'jobs',
    title: 'Jobs and rules',
    ru: 'Профессии и правила',
    level: 'A2',
    grades: [7, 9],
    icon: '👷',
    words: [
      ['pilot', 'пилот', '🧑‍✈️'],
      ['engineer', 'инженер'],
      ['programmer', 'программист', '🧑‍💻'],
      ['vet', 'ветеринар'],
      ['firefighter', 'пожарный', '🧑‍🚒'],
      ['police officer', 'полицейский', '👮'],
      ['scientist', 'учёный', '🧑‍🔬'],
      ['artist', 'художник', '🧑‍🎨'],
      ['lawyer', 'юрист'],
      ['builder', 'строитель', '👷'],
      ['uniform', 'форма (одежда)'],
      ['salary', 'зарплата', '💵'],
      ['office', 'офис', '🏢'],
      ['earn', 'зарабатывать'],
      ['wear', 'носить (одежду)'],
      ['rule', 'правило'],
      ['allowed', 'разрешено'],
      ['early', 'рано'],
      ['weekend', 'выходные'],
      ['career', 'карьера'],
    ],
    phrases: [
      ['Pilots have to wear a uniform.', 'Пилоты должны носить форму.'],
      ['Do you have to get up early?', 'Тебе приходится рано вставать?'],
      ['We don’t have to go to school on Sunday.', 'В воскресенье нам не нужно идти в школу.'],
      ['She has to work at the weekend.', 'Ей приходится работать по выходным.'],
      ['I want to be a programmer.', 'Я хочу стать программистом.'],
      ['Firefighters have to be brave.', 'Пожарные должны быть смелыми.'],
      ['Vets help animals.', 'Ветеринары помогают животным.'],
      ['He earns a good salary.', 'Он хорошо зарабатывает.'],
      ['Phones aren’t allowed in class.', 'Телефоны на уроке запрещены.'],
      ['What do you want to be?', 'Кем ты хочешь стать?'],
    ],
    grammar: {
      title: 'have to / don’t have to',
      rule: ['have to — приходится, надо (по обстоятельствам): I have to get up early. She has to work.', 'don’t have to — не нужно, необязательно: You don’t have to come.', 'Сравните: mustn’t — нельзя! don’t have to — можно не делать.', 'Вопрос: Do you have to…? Does he have to…?'],
      gaps: [
        ['Pilots ___ wear a uniform.', ['have to', 'has to', 'haves to'], 0, 'Пилоты должны носить форму.'],
        ['She ___ work at the weekend.', ['has to', 'have to', 'must to'], 0, 'Ей приходится работать в выходные.'],
        ['It’s Sunday! You ___ get up early.', ['don’t have to', 'mustn’t', 'have to'], 0, 'Сегодня воскресенье! Можно не вставать рано.'],
        ['___ you have to wear a uniform at school?', ['Do', 'Does', 'Have'], 0, 'Тебе нужно носить форму в школе?'],
        ['Does he have to ___ the exam?', ['take', 'takes', 'taking'], 0, 'Ему нужно сдавать экзамен?'],
        ['You ___ smoke here. It’s dangerous!', ['mustn’t', 'don’t have to', 'have to'], 0, 'Здесь нельзя курить. Это опасно!'],
        ['We ___ do homework in the holidays.', ['don’t have to', 'doesn’t have to', 'not have to'], 0, 'На каникулах нам не нужно делать уроки.'],
        ['I want ___ a vet.', ['to be', 'be', 'being'], 0, 'Я хочу стать ветеринаром.'],
        ['My dad ___ to drive to work every day.', ['has', 'have', 'is'], 0, 'Папе каждый день приходится ездить на работу.'],
        ['Phones aren’t ___ in class.', ['allowed', 'allow', 'allowing'], 0, 'Телефоны на уроке запрещены.'],
      ],
    },
  },
  {
    id: 'fun',
    title: 'Films and music',
    ru: 'Кино и музыка',
    level: 'A2',
    grades: [7, 9],
    icon: '🎬',
    words: [
      ['film', 'фильм', '🎞️'],
      ['cartoon', 'мультфильм'],
      ['comedy', 'комедия', '😂'],
      ['horror film', 'фильм ужасов', '🧟'],
      ['actor', 'актёр', '🎭'],
      ['band', 'группа (музыкальная)', '🎸'],
      ['concert', 'концерт', '🎤'],
      ['song', 'песня', '🎵'],
      ['album', 'альбом'],
      ['ticket', 'билет', '🎟️'],
      ['enjoy', 'наслаждаться, нравиться'],
      ['hate', 'ненавидеть'],
      ['mind', 'возражать'],
      ['want', 'хотеть'],
      ['would like', 'хотел бы'],
      ['learn', 'учиться'],
      ['decide', 'решать'],
      ['agree', 'соглашаться'],
      ['finish', 'заканчивать'],
      ['practise', 'тренироваться'],
    ],
    phrases: [
      ['I enjoy watching comedies.', 'Мне нравится смотреть комедии.'],
      ['I want to go to the concert.', 'Я хочу пойти на концерт.'],
      ['Would you like to see a film?', 'Хочешь посмотреть фильм?'],
      ['She hates waiting.', 'Она терпеть не может ждать.'],
      ['Do you mind closing the window?', 'Не мог бы ты закрыть окно?'],
      ['I decided to learn the guitar.', 'Я решил научиться играть на гитаре.'],
      ['He finished doing his homework.', 'Он закончил делать уроки.'],
      ['We agreed to meet at six.', 'Мы договорились встретиться в шесть.'],
      ['I need to practise every day.', 'Мне нужно тренироваться каждый день.'],
      ['What kind of music do you like?', 'Какую музыку ты любишь?'],
    ],
    grammar: {
      title: 'Глагол + -ing или + to',
      rule: ['После enjoy, finish, mind, hate, practise, stop — глагол с -ing: I enjoy dancing.', 'После want, would like, decide, agree, hope, learn, need — to + глагол: I want to dance.', 'like и love — можно и так, и так: I like swimming / I like to swim.'],
      gaps: [
        ['I enjoy ___ films.', ['watching', 'to watch', 'watch'], 0, 'Я люблю смотреть фильмы.'],
        ['I want ___ to the concert.', ['to go', 'going', 'go'], 0, 'Я хочу пойти на концерт.'],
        ['She finished ___ her homework.', ['doing', 'to do', 'do'], 0, 'Она закончила делать уроки.'],
        ['We decided ___ a band.', ['to start', 'starting', 'start'], 0, 'Мы решили собрать группу.'],
        ['Would you like ___ some tea?', ['to have', 'having', 'have'], 0, 'Хочешь чаю?'],
        ['Do you mind ___ the window?', ['opening', 'to open', 'open'], 0, 'Не мог бы ты открыть окно?'],
        ['He hates ___ for the bus.', ['waiting', 'to waiting', 'wait'], 0, 'Он терпеть не может ждать автобус.'],
        ['They agreed ___ us.', ['to help', 'helping', 'help'], 0, 'Они согласились нам помочь.'],
        ['You need ___ every day.', ['to practise', 'practising', 'practise'], 0, 'Тебе нужно заниматься каждый день.'],
        ['Stop ___ so loudly!', ['talking', 'to talk', 'talk'], 0, 'Хватит так громко разговаривать!'],
      ],
    },
  },
];
