import type { Unit } from '../types.js';

// B1 (ОГЭ и база ЕГЭ): Present Perfect, for/since, условные предложения, страдательный залог,
// придаточные определительные, used to, косвенная речь, фразовые глаголы, словообразование.
export const B1: Unit[] = [
  {
    id: 'experience',
    title: 'Have you ever…?',
    ru: 'Опыт и впечатления',
    level: 'B1',
    grades: [8, 9],
    icon: '🌍',
    words: [
      ['ever', 'когда-нибудь'],
      ['never', 'никогда'],
      ['been', 'был (be)'],
      ['seen', 'видел (see)'],
      ['done', 'сделал (do)'],
      ['eaten', 'ел (eat)'],
      ['flown', 'летал (fly)'],
      ['tried', 'пробовал'],
      ['met', 'встречал (meet)'],
      ['ridden', 'катался (ride)'],
      ['climbed', 'взбирался'],
      ['abroad', 'за границей', '✈️'],
      ['volcano', 'вулкан', '🌋'],
      ['waterfall', 'водопад'],
      ['famous', 'знаменитый', '⭐'],
      ['experience', 'опыт, впечатление'],
      ['amazing', 'потрясающий', '🤩'],
      ['once', 'однажды, один раз'],
      ['twice', 'дважды'],
      ['in my life', 'в жизни'],
    ],
    phrases: [
      ['Have you ever been to London?', 'Ты когда-нибудь был в Лондоне?'],
      ['I have never flown on a plane.', 'Я никогда не летал на самолёте.'],
      ['She has seen this film twice.', 'Она смотрела этот фильм дважды.'],
      ['Have you ever tried sushi?', 'Ты когда-нибудь пробовал суши?'],
      ['Yes, I have. I tried it last year.', 'Да. Я пробовал в прошлом году.'],
      ['He has met a famous actor.', 'Он встречал известного актёра.'],
      ['We have never climbed a mountain.', 'Мы никогда не взбирались на гору.'],
      ['It was an amazing experience.', 'Это были потрясающие впечатления.'],
      ['My parents have been abroad many times.', 'Мои родители много раз были за границей.'],
      ['Has she ever ridden a horse?', 'Она когда-нибудь каталась на лошади?'],
    ],
    grammar: {
      title: 'Present Perfect: опыт (ever, never)',
      rule: ['have / has + третья форма глагола: I have seen, she has been.', 'Опыт «за всю жизнь»: Have you ever been to Paris? I have never tried it.', 'Конкретное время в прошлом — уже Past Simple: I went there last year.', 'been to — был и вернулся; gone to — уехал и ещё там.'],
      gaps: [
        ['Have you ever ___ to London?', ['been', 'gone', 'was'], 0, 'Ты когда-нибудь был в Лондоне?'],
        ['I have never ___ on a plane.', ['flown', 'flew', 'fly'], 0, 'Я никогда не летал на самолёте.'],
        ['She ___ seen this film twice.', ['has', 'have', 'is'], 0, 'Она дважды смотрела этот фильм.'],
        ['___ you ever tried sushi?', ['Have', 'Did', 'Has'], 0, 'Ты когда-нибудь пробовал суши?'],
        ['I tried it ___ year.', ['last', 'ever', 'never'], 0, 'Я пробовал его в прошлом году.'],
        ['We have ___ climbed a mountain.', ['never', 'ever', 'yet'], 0, 'Мы никогда не взбирались на гору.'],
        ['He ___ a famous actor in 2020.', ['met', 'has met', 'meet'], 0, 'В 2020 году он встретил известного актёра.'],
        ['Mum isn’t here. She has ___ to the shop.', ['gone', 'been', 'went'], 0, 'Мамы нет. Она ушла в магазин.'],
        ['Have they ever ___ a horse?', ['ridden', 'rode', 'ride'], 0, 'Они когда-нибудь катались на лошади?'],
        ['Has he ever ___ abroad? — No, he hasn’t.', ['been', 'be', 'was'], 0, 'Он бывал за границей? — Нет.'],
      ],
    },
  },
  {
    id: 'news',
    title: 'What’s new?',
    ru: 'Новости и перемены',
    level: 'B1',
    grades: [8, 9],
    icon: '📰',
    words: [
      ['already', 'уже'],
      ['yet', 'ещё (в отрицании), уже (в вопросе)'],
      ['just', 'только что'],
      ['recently', 'недавно'],
      ['news', 'новости', '📰'],
      ['change', 'менять, изменение'],
      ['move', 'переезжать'],
      ['finish', 'заканчивать'],
      ['start', 'начинать'],
      ['buy', 'покупать'],
      ['sell', 'продавать'],
      ['grow', 'расти'],
      ['lose', 'терять'],
      ['repair', 'чинить', '🔧'],
      ['paint', 'красить', '🖌️'],
      ['message', 'сообщение', '💬'],
      ['decide', 'решать'],
      ['arrive', 'прибывать'],
      ['leave', 'уезжать, уходить'],
      ['so far', 'пока что, до сих пор'],
    ],
    phrases: [
      ['I have already done my homework.', 'Я уже сделал домашнее задание.'],
      ['She has just come home.', 'Она только что пришла домой.'],
      ['We haven’t seen this film yet.', 'Мы ещё не видели этот фильм.'],
      ['Have you finished yet?', 'Ты уже закончил?'],
      ['They have moved to a new flat.', 'Они переехали в новую квартиру.'],
      ['Look! Someone has painted the door.', 'Смотри! Кто-то покрасил дверь.'],
      ['I have lost my phone. Have you seen it?', 'Я потерял телефон. Ты его не видел?'],
      ['He bought a bike yesterday.', 'Вчера он купил велосипед.'],
      ['Have you heard the news?', 'Ты слышал новость?'],
      ['So far we have learned ten words.', 'Пока что мы выучили десять слов.'],
    ],
    grammar: {
      title: 'Present Perfect или Past Simple',
      rule: ['Present Perfect — результат важен сейчас, время не названо: I have lost my keys (и их нет).', 'already и just — между have и глаголом; yet — в конце вопроса и отрицания.', 'Past Simple — когда названо время: yesterday, last week, in 2019, ago.'],
      gaps: [
        ['I have ___ done my homework.', ['already', 'yet', 'ago'], 0, 'Я уже сделал уроки.'],
        ['We haven’t seen this film ___.', ['yet', 'already', 'just'], 0, 'Мы ещё не видели этот фильм.'],
        ['She has ___ come home.', ['just', 'yet', 'ever'], 0, 'Она только что пришла домой.'],
        ['He ___ a bike yesterday.', ['bought', 'has bought', 'buys'], 0, 'Вчера он купил велосипед.'],
        ['I ___ my phone. I can’t find it.', ['have lost', 'lost yesterday', 'lose'], 0, 'Я потерял телефон. Не могу найти.'],
        ['Have you finished ___?', ['yet', 'already', 'just'], 0, 'Ты уже закончил?'],
        ['They ___ to Kazan two years ago.', ['moved', 'have moved', 'move'], 0, 'Два года назад они переехали в Казань.'],
        ['Look! Someone ___ the door.', ['has painted', 'painted yesterday', 'paints'], 0, 'Смотри! Кто-то покрасил дверь.'],
        ['___ you heard the news?', ['Have', 'Did', 'Are'], 0, 'Ты слышал новость?'],
        ['When ___ you arrive?', ['did', 'have', 'has'], 0, 'Когда ты приехал?'],
      ],
    },
  },
  {
    id: 'howlong',
    title: 'How long?',
    ru: 'Как давно?',
    level: 'B1',
    grades: [8, 10],
    icon: '⏳',
    words: [
      ['for', 'в течение'],
      ['since', 'с (какого-то момента)'],
      ['how long', 'как долго'],
      ['know', 'знать'],
      ['live', 'жить'],
      ['work', 'работать'],
      ['study', 'изучать'],
      ['collect', 'коллекционировать'],
      ['wait', 'ждать'],
      ['own', 'владеть'],
      ['century', 'век'],
      ['decade', 'десятилетие'],
      ['childhood', 'детство'],
      ['neighbour', 'сосед'],
      ['member', 'участник, член (клуба)'],
      ['club', 'клуб, секция'],
      ['stamp', 'марка', '📮'],
      ['coin', 'монета', '🪙'],
      ['ages', 'целую вечность'],
      ['lately', 'в последнее время'],
    ],
    phrases: [
      ['How long have you lived here?', 'Как долго ты здесь живёшь?'],
      ['I have lived here since 2015.', 'Я живу здесь с 2015 года.'],
      ['We have known each other for five years.', 'Мы знаем друг друга пять лет.'],
      ['She has been a member of the club since May.', 'Она в клубе с мая.'],
      ['I haven’t seen him for ages.', 'Я не видел его целую вечность.'],
      ['He has collected coins since his childhood.', 'Он собирает монеты с детства.'],
      ['They have had this car for ten years.', 'У них эта машина десять лет.'],
      ['How long have you studied English?', 'Сколько ты учишь английский?'],
      ['I have been waiting for an hour.', 'Я жду уже час.'],
      ['It has been cold lately.', 'В последнее время холодно.'],
    ],
    grammar: {
      title: 'for и since, How long…?',
      rule: ['Действие началось в прошлом и длится до сих пор — Present Perfect: I have lived here for five years.', 'for + период: for two weeks, for ages. since + начало: since 2015, since Monday, since I was six.', 'Процесс подчёркиваем Present Perfect Continuous: I have been waiting for an hour.'],
      gaps: [
        ['I have lived here ___ 2015.', ['since', 'for', 'from'], 0, 'Я живу здесь с 2015 года.'],
        ['We have known each other ___ five years.', ['for', 'since', 'during'], 0, 'Мы знакомы пять лет.'],
        ['How long ___ you had this phone?', ['have', 'did', 'do'], 0, 'Сколько у тебя этот телефон?'],
        ['She has been in the club ___ May.', ['since', 'for', 'ago'], 0, 'Она в клубе с мая.'],
        ['I haven’t seen him ___ ages.', ['for', 'since', 'in'], 0, 'Я не видел его целую вечность.'],
        ['He ___ coins since he was seven.', ['has collected', 'collects', 'collected'], 0, 'Он собирает монеты с семи лет.'],
        ['I have been ___ for an hour!', ['waiting', 'waited', 'wait'], 0, 'Я жду уже час!'],
        ['They ___ here for ten years.', ['have lived', 'live', 'are living'], 0, 'Они живут здесь десять лет.'],
        ['How long have you ___ English?', ['studied', 'study', 'studying'], 0, 'Сколько ты учишь английский?'],
        ['It ___ cold lately.', ['has been', 'is', 'was been'], 0, 'В последнее время холодно.'],
      ],
    },
  },
  {
    id: 'nature',
    title: 'Our planet',
    ru: 'Экология',
    level: 'B1',
    grades: [8, 10],
    icon: '🌿',
    words: [
      ['environment', 'окружающая среда'],
      ['pollution', 'загрязнение', '🏭'],
      ['recycle', 'перерабатывать', '♻️'],
      ['rubbish', 'мусор', '🗑️'],
      ['plastic', 'пластик'],
      ['protect', 'защищать', '🛡️'],
      ['save', 'спасать, экономить'],
      ['waste', 'тратить впустую'],
      ['energy', 'энергия', '⚡'],
      ['climate', 'климат'],
      ['global warming', 'глобальное потепление', '🌡️'],
      ['air', 'воздух'],
      ['endangered', 'находящийся под угрозой'],
      ['species', 'вид (животных)'],
      ['solar panel', 'солнечная батарея', '☀️'],
      ['unless', 'если не'],
      ['as soon as', 'как только'],
      ['flood', 'наводнение', '🌊'],
      ['disappear', 'исчезать'],
      ['nature', 'природа'],
    ],
    phrases: [
      ['If it rains, we will stay at home.', 'Если пойдёт дождь, мы останемся дома.'],
      ['If we recycle paper, we will save trees.', 'Если перерабатывать бумагу, мы спасём деревья.'],
      ['We must protect nature.', 'Мы должны защищать природу.'],
      ['Don’t waste water.', 'Не трать воду зря.'],
      ['Unless we act now, many species will disappear.', 'Если не действовать сейчас, многие виды исчезнут.'],
      ['I will call you as soon as I get home.', 'Позвоню, как только приду домой.'],
      ['If you heat ice, it melts.', 'Если нагреть лёд, он тает.'],
      ['Plastic bags pollute the ocean.', 'Пластиковые пакеты загрязняют океан.'],
      ['Turn off the light when you leave.', 'Выключай свет, когда уходишь.'],
      ['The air in the city is dirty.', 'Воздух в городе грязный.'],
    ],
    grammar: {
      title: 'Условные предложения 0 и 1 типа',
      rule: ['Тип 0 — всегда так (законы природы): If you heat ice, it melts.', 'Тип 1 — реальное будущее: If + Present Simple, will + глагол: If it rains, we will stay home.', 'После if, unless, when, as soon as будущее не ставим: as soon as I get home (не will get).'],
      gaps: [
        ['If it ___ tomorrow, we will stay at home.', ['rains', 'will rain', 'rained'], 0, 'Если завтра пойдёт дождь, мы останемся дома.'],
        ['If we recycle paper, we ___ trees.', ['will save', 'save will', 'saved'], 0, 'Если перерабатывать бумагу, мы спасём деревья.'],
        ['If you heat ice, it ___.', ['melts', 'will melted', 'melted'], 0, 'Если нагреть лёд, он тает.'],
        ['I will call you as soon as I ___ home.', ['get', 'will get', 'got'], 0, 'Позвоню, как только приду домой.'],
        ['___ we act now, many animals will disappear.', ['Unless', 'If', 'When'], 0, 'Если не действовать сейчас, многие животные исчезнут.'],
        ['If you ___ hurry, you will miss the bus.', ['don’t', 'won’t', 'didn’t'], 0, 'Если не поторопишься, опоздаешь на автобус.'],
        ['What will you do if you ___ the exam?', ['pass', 'will pass', 'passed'], 0, 'Что будешь делать, если сдашь экзамен?'],
        ['If she studies hard, she ___ to university.', ['will go', 'goes will', 'went'], 0, 'Если она будет усердно учиться, поступит в университет.'],
        ['When the sun ___, the snow melts.', ['shines', 'will shine', 'shone'], 0, 'Когда светит солнце, снег тает.'],
        ['We ___ the planet if we don’t stop pollution.', ['will lose', 'lose will', 'lost'], 0, 'Мы потеряем планету, если не остановим загрязнение.'],
      ],
    },
  },
  {
    id: 'dreams',
    title: 'If I were…',
    ru: 'Мечты и «если бы»',
    level: 'B1',
    grades: [8, 11],
    icon: '💭',
    words: [
      ['dream', 'мечта, мечтать', '💭'],
      ['rich', 'богатый', '💰'],
      ['famous', 'знаменитый'],
      ['invisible', 'невидимый', '👻'],
      ['superpower', 'суперсила', '🦸'],
      ['island', 'остров', '🏝️'],
      ['spaceship', 'космический корабль', '🛸'],
      ['lottery', 'лотерея', '🎰'],
      ['wish', 'желать'],
      ['imagine', 'представлять'],
      ['choose', 'выбирать'],
      ['would', 'бы'],
      ['could', 'мог бы'],
      ['instead', 'вместо этого'],
      ['advice', 'совет'],
      ['charity', 'благотворительность'],
      ['mansion', 'особняк'],
      ['president', 'президент'],
      ['travel the world', 'путешествовать по миру', '🌍'],
      ['own', 'собственный'],
    ],
    phrases: [
      ['If I were rich, I would travel the world.', 'Если бы я был богат, я бы путешествовал по миру.'],
      ['If I had a superpower, I would fly.', 'Если бы у меня была суперсила, я бы летал.'],
      ['What would you do if you won the lottery?', 'Что бы ты сделал, если бы выиграл в лотерею?'],
      ['If I were you, I would tell the truth.', 'На твоём месте я бы сказал правду.'],
      ['I would give some money to charity.', 'Я бы отдал часть денег на благотворительность.'],
      ['I wish I could speak Chinese.', 'Жаль, что я не говорю по-китайски.'],
      ['Imagine you were invisible.', 'Представь, что ты невидимый.'],
      ['She would buy an island.', 'Она бы купила остров.'],
      ['If I lived by the sea, I would swim every day.', 'Если бы я жил у моря, я бы плавал каждый день.'],
      ['I wouldn’t change anything.', 'Я бы ничего не менял.'],
    ],
    grammar: {
      title: 'Условные предложения 2 типа',
      rule: ['Нереальное или маловероятное: If + Past Simple, would + глагол: If I had wings, I would fly.', 'С to be — were для всех: If I were you… If she were here…', 'Совет: If I were you, I would… Сожаление: I wish I could…'],
      gaps: [
        ['If I ___ rich, I would buy a mansion.', ['were', 'am', 'will be'], 0, 'Если бы я был богат, я бы купил особняк.'],
        ['If I had a superpower, I ___ fly.', ['would', 'will', 'did'], 0, 'Если бы у меня была суперсила, я бы летал.'],
        ['What would you do if you ___ the lottery?', ['won', 'win', 'will win'], 0, 'Что бы ты сделал, если бы выиграл в лотерею?'],
        ['If I ___ you, I would tell the truth.', ['were', 'was be', 'am'], 0, 'На твоём месте я бы сказал правду.'],
        ['She ___ buy an island if she had money.', ['would', 'will', 'does'], 0, 'Она бы купила остров, если бы у неё были деньги.'],
        ['If he ___ harder, he would pass.', ['studied', 'studies', 'will study'], 0, 'Если бы он занимался усерднее, он бы сдал.'],
        ['I wish I ___ speak Chinese.', ['could', 'can', 'will'], 0, 'Жаль, что я не говорю по-китайски.'],
        ['If we lived by the sea, we ___ every day.', ['would swim', 'will swim', 'swam'], 0, 'Если бы мы жили у моря, мы бы плавали каждый день.'],
        ['I ___ change anything.', ['wouldn’t', 'won’t would', 'didn’t'], 0, 'Я бы ничего не менял.'],
        ['If you could ___ any animal, what would you be?', ['be', 'were', 'being'], 0, 'Если бы ты мог стать любым животным, кем бы ты был?'],
      ],
    },
  },
  {
    id: 'inventions',
    title: 'Inventions',
    ru: 'Изобретения',
    level: 'B1',
    grades: [8, 11],
    icon: '💡',
    words: [
      ['invent', 'изобретать', '💡'],
      ['invention', 'изобретение'],
      ['inventor', 'изобретатель'],
      ['discover', 'открывать (находить)'],
      ['design', 'проектировать'],
      ['build', 'строить', '🏗️'],
      ['produce', 'производить'],
      ['use', 'использовать'],
      ['wheel', 'колесо', '☸️'],
      ['telephone', 'телефон', '☎️'],
      ['light bulb', 'лампочка', '💡'],
      ['printer', 'принтер', '🖨️'],
      ['satellite', 'спутник', '🛰️'],
      ['internet', 'интернет', '🌐'],
      ['factory', 'завод', '🏭'],
      ['made of', 'сделан из'],
      ['made in', 'сделан в (стране)'],
      ['wood', 'дерево (материал)', '🪵'],
      ['metal', 'металл'],
      ['glass', 'стекло'],
    ],
    phrases: [
      ['The telephone was invented by Bell.', 'Телефон изобрёл Белл.'],
      ['Paper is made of wood.', 'Бумагу делают из дерева.'],
      ['These phones are made in China.', 'Эти телефоны производят в Китае.'],
      ['English is spoken all over the world.', 'На английском говорят по всему миру.'],
      ['The house was built in 1900.', 'Дом построили в 1900 году.'],
      ['America was discovered in 1492.', 'Америку открыли в 1492 году.'],
      ['The first satellite was launched in 1957.', 'Первый спутник запустили в 1957 году.'],
      ['Millions of cars are produced every year.', 'Каждый год выпускают миллионы машин.'],
      ['The bridge is being repaired.', 'Мост сейчас ремонтируют.'],
      ['Who was the light bulb invented by?', 'Кто изобрёл лампочку?'],
    ],
    grammar: {
      title: 'Страдательный залог',
      rule: ['Важно действие, а не кто делает: be + третья форма. Paper is made of wood.', 'Настоящее: is / are + V3. Прошлое: was / were + V3: The house was built in 1900.', 'Кем — by: The phone was invented by Bell.'],
      gaps: [
        ['The telephone ___ invented by Bell.', ['was', 'is', 'were'], 0, 'Телефон изобрёл Белл.'],
        ['Paper is made ___ wood.', ['of', 'by', 'from of'], 0, 'Бумагу делают из дерева.'],
        ['English ___ spoken all over the world.', ['is', 'are', 'was'], 0, 'На английском говорят по всему миру.'],
        ['These houses ___ built in 1990.', ['were', 'was', 'are'], 0, 'Эти дома построили в 1990 году.'],
        ['Millions of cars are ___ every year.', ['produced', 'produce', 'producing'], 0, 'Каждый год выпускают миллионы машин.'],
        ['The first satellite was ___ in 1957.', ['launched', 'launch', 'launching'], 0, 'Первый спутник запустили в 1957 году.'],
        ['The bridge is being ___ now.', ['repaired', 'repair', 'repairing'], 0, 'Мост сейчас ремонтируют.'],
        ['“Harry Potter” was written ___ J. K. Rowling.', ['by', 'of', 'from'], 0, '«Гарри Поттера» написала Джоан Роулинг.'],
        ['America ___ discovered in 1492.', ['was', 'were', 'is'], 0, 'Америку открыли в 1492 году.'],
        ['These phones ___ made in China.', ['are', 'is', 'was'], 0, 'Эти телефоны сделаны в Китае.'],
      ],
    },
  },
  {
    id: 'people2',
    title: 'People around us',
    ru: 'Люди вокруг нас',
    level: 'B1',
    grades: [8, 11],
    icon: '🧑‍🤝‍🧑',
    words: [
      ['who', 'который (о людях)'],
      ['which', 'который (о предметах)'],
      ['that', 'который (о людях и предметах)'],
      ['where', 'где (в котором)'],
      ['whose', 'чей'],
      ['classmate', 'одноклассник'],
      ['neighbour', 'сосед', '🏘️'],
      ['stranger', 'незнакомец'],
      ['relative', 'родственник'],
      ['colleague', 'коллега'],
      ['hero', 'герой', '🦸'],
      ['volunteer', 'волонтёр', '🙋'],
      ['reliable', 'надёжный'],
      ['patient', 'терпеливый'],
      ['curious', 'любопытный'],
      ['confident', 'уверенный в себе'],
      ['respect', 'уважать'],
      ['trust', 'доверять'],
      ['argue', 'спорить'],
      ['get on with', 'ладить с'],
    ],
    phrases: [
      ['This is the girl who won the competition.', 'Это девочка, которая выиграла конкурс.'],
      ['I lost the book which you gave me.', 'Я потерял книгу, которую ты мне дал.'],
      ['That’s the café where we met.', 'Это кафе, где мы познакомились.'],
      ['He is a friend whose dad is a pilot.', 'Это друг, чей папа — пилот.'],
      ['I get on well with my classmates.', 'Я хорошо лажу с одноклассниками.'],
      ['A volunteer is a person who helps for free.', 'Волонтёр — человек, который помогает бесплатно.'],
      ['Don’t talk to strangers.', 'Не разговаривай с незнакомцами.'],
      ['My grandad is the person I respect most.', 'Дедушка — человек, которого я уважаю больше всех.'],
      ['We sometimes argue, but we are friends.', 'Мы иногда спорим, но мы друзья.'],
      ['She is very patient and reliable.', 'Она очень терпеливая и надёжная.'],
    ],
    grammar: {
      title: 'Придаточные: who, which, that, where, whose',
      rule: ['who — о людях: the girl who won.', 'which — о предметах и животных: the book which you gave me.', 'that — и о людях, и о предметах. where — о месте. whose — чей.'],
      gaps: [
        ['This is the girl ___ won the race.', ['who', 'which', 'where'], 0, 'Это девочка, которая выиграла забег.'],
        ['I lost the book ___ you gave me.', ['which', 'who', 'where'], 0, 'Я потерял книгу, которую ты мне дал.'],
        ['That’s the café ___ we met.', ['where', 'which', 'who'], 0, 'Это кафе, где мы познакомились.'],
        ['He is the boy ___ dad is a pilot.', ['whose', 'who', 'which'], 0, 'Это мальчик, чей папа — пилот.'],
        ['A volunteer is a person ___ helps people.', ['who', 'which', 'whose'], 0, 'Волонтёр — человек, который помогает людям.'],
        ['The dog ___ lives next door is huge.', ['that', 'who', 'where'], 0, 'Собака, которая живёт по соседству, огромная.'],
        ['This is the town ___ I was born.', ['where', 'which', 'who'], 0, 'Это город, где я родился.'],
        ['I get on well ___ my sister.', ['with', 'to', 'by'], 0, 'Я хорошо лажу с сестрой.'],
        ['Is this the phone ___ you bought yesterday?', ['which', 'who', 'whose'], 0, 'Это телефон, который ты вчера купил?'],
        ['The teacher ___ helped me is very patient.', ['who', 'which', 'whose'], 0, 'Учитель, который мне помог, очень терпеливый.'],
      ],
    },
  },
  {
    id: 'childhood',
    title: 'When I was little',
    ru: 'Детство и привычки',
    level: 'B1',
    grades: [8, 11],
    icon: '🧸',
    words: [
      ['used to', 'раньше (бывало)'],
      ['childhood', 'детство'],
      ['kindergarten', 'детский сад'],
      ['toy', 'игрушка', '🧸'],
      ['swing', 'качели'],
      ['habit', 'привычка'],
      ['remember', 'помнить'],
      ['forget', 'забывать'],
      ['believe', 'верить'],
      ['scared of', 'бояться'],
      ['afraid of', 'бояться (боящийся)'],
      ['grow up', 'расти, взрослеть'],
      ['tidy', 'опрятный, убирать'],
      ['naughty', 'непослушный'],
      ['cry', 'плакать'],
      ['dark', 'темнота'],
      ['nowadays', 'в наши дни'],
      ['any more', 'больше не'],
      ['still', 'всё ещё'],
      ['change', 'меняться'],
    ],
    phrases: [
      ['I used to be afraid of the dark.', 'Раньше я боялся темноты.'],
      ['We used to live in a village.', 'Раньше мы жили в деревне.'],
      ['Did you use to play with dolls?', 'Ты раньше играла в куклы?'],
      ['He didn’t use to like vegetables.', 'Раньше он не любил овощи.'],
      ['I don’t believe in monsters any more.', 'Я больше не верю в монстров.'],
      ['She still loves cartoons.', 'Она всё ещё любит мультики.'],
      ['When I grow up, I want to be a doctor.', 'Когда вырасту, хочу стать врачом.'],
      ['I remember my first day at school.', 'Я помню свой первый день в школе.'],
      ['Children were more naughty then.', 'Тогда дети были более непослушными.'],
      ['Nowadays kids have phones.', 'В наши дни у детей есть телефоны.'],
    ],
    grammar: {
      title: 'used to — «раньше, а теперь нет»',
      rule: ['used to + глагол — раньше было (а теперь нет): I used to live in a village.', 'Отрицание: didn’t use to. Вопрос: Did you use to…? (без -d!)', 'Для привычек сейчас — Present Simple, для одного случая в прошлом — Past Simple.'],
      gaps: [
        ['I ___ be afraid of the dark.', ['used to', 'use to', 'was used'], 0, 'Раньше я боялся темноты.'],
        ['Did you ___ play with dolls?', ['use to', 'used to', 'using to'], 0, 'Ты раньше играла в куклы?'],
        ['He didn’t ___ like vegetables.', ['use to', 'used to', 'uses to'], 0, 'Раньше он не любил овощи.'],
        ['We used to ___ in a village.', ['live', 'living', 'lived'], 0, 'Раньше мы жили в деревне.'],
        ['I don’t believe in monsters ___.', ['any more', 'still', 'yet more'], 0, 'Я больше не верю в монстров.'],
        ['She ___ loves cartoons.', ['still', 'any more', 'yet'], 0, 'Она всё ещё любит мультики.'],
        ['When I ___ up, I want to be a doctor.', ['grow', 'will grow', 'grew'], 0, 'Когда вырасту, хочу стать врачом.'],
        ['Are you scared ___ spiders?', ['of', 'from', 'about'], 0, 'Ты боишься пауков?'],
        ['My dad ___ to play football every Sunday.', ['used', 'uses', 'use'], 0, 'Раньше папа каждое воскресенье играл в футбол.'],
        ['I ___ my first day at school very well.', ['remember', 'am remembering', 'remembers'], 0, 'Я хорошо помню свой первый день в школе.'],
      ],
    },
  },
  {
    id: 'reported',
    title: 'She said…',
    ru: 'Косвенная речь',
    level: 'B1',
    grades: [9, 11],
    icon: '💬',
    words: [
      ['say', 'сказать (что-то)'],
      ['tell', 'сказать (кому-то), рассказать'],
      ['ask', 'спросить, попросить'],
      ['answer', 'ответить'],
      ['explain', 'объяснять'],
      ['promise', 'обещать'],
      ['agree', 'соглашаться'],
      ['refuse', 'отказываться'],
      ['complain', 'жаловаться'],
      ['whisper', 'шептать', '🤫'],
      ['rumour', 'слух'],
      ['secret', 'секрет', '🔒'],
      ['truth', 'правда'],
      ['lie', 'ложь, лгать'],
      ['message', 'сообщение', '💬'],
      ['the day before', 'накануне'],
      ['the next day', 'на следующий день'],
      ['then', 'тогда'],
      ['there', 'там'],
      ['whether', 'ли'],
    ],
    phrases: [
      ['She said that she was tired.', 'Она сказала, что устала.'],
      ['He told me that he liked pizza.', 'Он сказал мне, что любит пиццу.'],
      ['Tom said he would come.', 'Том сказал, что придёт.'],
      ['She asked me where I lived.', 'Она спросила меня, где я живу.'],
      ['He asked if I was hungry.', 'Он спросил, голоден ли я.'],
      ['The teacher told us to be quiet.', 'Учитель велел нам вести себя тихо.'],
      ['Mum asked me not to be late.', 'Мама попросила меня не опаздывать.'],
      ['They said they had seen the film.', 'Они сказали, что видели этот фильм.'],
      ['Can you keep a secret?', 'Ты умеешь хранить секреты?'],
      ['Tell me the truth.', 'Скажи мне правду.'],
    ],
    grammar: {
      title: 'Косвенная речь',
      rule: ['Время «отступает» назад: am → was, like → liked, will → would, can → could, have done → had done.', 'say — без кого: She said that… tell — с кем: She told me that…', 'Вопросы: She asked where I lived (прямой порядок слов); «ли» — if / whether.', 'Просьбы: told me to go, asked me not to be late.'],
      gaps: [
        ['“I am tired.” — She said that she ___ tired.', ['was', 'is', 'were'], 0, 'Она сказала, что устала.'],
        ['He ___ me that he liked pizza.', ['told', 'said', 'spoke'], 0, 'Он сказал мне, что любит пиццу.'],
        ['She ___ that she would come.', ['said', 'told', 'asked'], 0, 'Она сказала, что придёт.'],
        ['“I will help.” — Tom said he ___ help.', ['would', 'will', 'can'], 0, 'Том сказал, что поможет.'],
        ['She asked me where I ___.', ['lived', 'do live', 'did live'], 0, 'Она спросила, где я живу.'],
        ['He asked ___ I was hungry.', ['if', 'that', 'what'], 0, 'Он спросил, голоден ли я.'],
        ['The teacher told us ___ quiet.', ['to be', 'be', 'being'], 0, 'Учитель велел нам вести себя тихо.'],
        ['Mum asked me ___ be late.', ['not to', 'to not', 'don’t'], 0, 'Мама попросила меня не опаздывать.'],
        ['“I can swim.” — He said he ___ swim.', ['could', 'can', 'could to'], 0, 'Он сказал, что умеет плавать.'],
        ['They said they ___ the film before.', ['had seen', 'have seen', 'see'], 0, 'Они сказали, что видели этот фильм раньше.'],
      ],
    },
  },
  {
    id: 'phrasal',
    title: 'Phrasal verbs',
    ru: 'Фразовые глаголы',
    level: 'B1',
    grades: [9, 11],
    icon: '🧩',
    words: [
      ['get up', 'вставать'],
      ['look for', 'искать', '🔍'],
      ['look after', 'присматривать, заботиться'],
      ['look forward to', 'с нетерпением ждать'],
      ['give up', 'бросать (привычку), сдаваться'],
      ['turn on', 'включать'],
      ['turn off', 'выключать'],
      ['put on', 'надевать'],
      ['take off', 'снимать (одежду), взлетать'],
      ['find out', 'узнавать'],
      ['grow up', 'вырастать'],
      ['run out of', 'заканчиваться (о запасе)'],
      ['come back', 'возвращаться'],
      ['set off', 'отправляться в путь'],
      ['pick up', 'поднимать, забирать'],
      ['go on', 'продолжать'],
      ['make up', 'выдумывать, мириться'],
      ['fill in', 'заполнять (анкету)'],
      ['look up', 'искать (в словаре)'],
      ['get on', 'садиться (в транспорт)'],
    ],
    phrases: [
      ['I’m looking for my keys.', 'Я ищу ключи.'],
      ['Can you look after my cat?', 'Можешь присмотреть за моей кошкой?'],
      ['I look forward to seeing you.', 'С нетерпением жду встречи.'],
      ['Don’t give up!', 'Не сдавайся!'],
      ['Turn off the light, please.', 'Выключи свет, пожалуйста.'],
      ['Put on your coat, it’s cold.', 'Надень пальто, холодно.'],
      ['The plane took off at six.', 'Самолёт взлетел в шесть.'],
      ['We have run out of milk.', 'У нас закончилось молоко.'],
      ['Look up this word in the dictionary.', 'Посмотри это слово в словаре.'],
      ['Please fill in this form.', 'Пожалуйста, заполните эту анкету.'],
    ],
    grammar: {
      title: 'Фразовые глаголы',
      rule: ['Глагол + частица = новое значение: look (смотреть) → look for (искать), look after (заботиться).', 'Местоимение — между глаголом и частицей: turn it off, put them on.', 'После look forward to — глагол с -ing: I look forward to meeting you.'],
      gaps: [
        ['I’m looking ___ my phone. Have you seen it?', ['for', 'after', 'up'], 0, 'Я ищу телефон. Ты его не видел?'],
        ['Can you look ___ my dog this weekend?', ['after', 'for', 'at'], 0, 'Присмотришь за собакой на выходных?'],
        ['Never give ___! You can do it!', ['up', 'off', 'in'], 0, 'Никогда не сдавайся! У тебя получится!'],
        ['It’s cold. Put ___ your hat.', ['on', 'off', 'up'], 0, 'Холодно. Надень шапку.'],
        ['Turn ___ the TV, I’m trying to sleep.', ['off', 'on', 'up'], 0, 'Выключи телевизор, я пытаюсь заснуть.'],
        ['We have run out ___ sugar.', ['of', 'off', 'from'], 0, 'У нас закончился сахар.'],
        ['I look forward to ___ you.', ['seeing', 'see', 'to see'], 0, 'С нетерпением жду встречи.'],
        ['Look ___ the word in a dictionary.', ['up', 'for', 'after'], 0, 'Посмотри слово в словаре.'],
        ['The plane took ___ on time.', ['off', 'on', 'up'], 0, 'Самолёт взлетел вовремя.'],
        ['The light is too bright. Turn ___ off.', ['it', 'him', 'its'], 0, 'Свет слишком яркий. Выключи его.'],
      ],
    },
  },
  {
    id: 'wordbuild',
    title: 'Word building',
    ru: 'Словообразование (ОГЭ, ЕГЭ)',
    level: 'B1',
    grades: [9, 11],
    icon: '🔤',
    words: [
      ['happiness', 'счастье'],
      ['kindness', 'доброта'],
      ['impossible', 'невозможный'],
      ['unhappy', 'несчастный'],
      ['careful', 'осторожный'],
      ['careless', 'небрежный'],
      ['useful', 'полезный'],
      ['useless', 'бесполезный'],
      ['national', 'национальный'],
      ['invention', 'изобретение'],
      ['decision', 'решение'],
      ['development', 'развитие'],
      ['actor', 'актёр', '🎭'],
      ['writer', 'писатель', '✍️'],
      ['friendly', 'дружелюбный'],
      ['dangerous', 'опасный', '⚠️'],
      ['beautiful', 'красивый'],
      ['successful', 'успешный'],
      ['difference', 'разница'],
      ['disagree', 'не соглашаться'],
    ],
    phrases: [
      ['He is a famous actor.', 'Он известный актёр.'],
      ['Be careful on the road.', 'Будь осторожен на дороге.'],
      ['It is impossible to do it in one day.', 'Это невозможно сделать за один день.'],
      ['The invention of the telephone changed the world.', 'Изобретение телефона изменило мир.'],
      ['Our neighbours are very friendly.', 'Наши соседи очень дружелюбные.'],
      ['Swimming here is dangerous.', 'Плавать здесь опасно.'],
      ['She made a difficult decision.', 'Она приняла трудное решение.'],
      ['Thank you for your kindness.', 'Спасибо за вашу доброту.'],
      ['I disagree with you.', 'Я с тобой не согласен.'],
      ['What is the difference?', 'В чём разница?'],
    ],
    grammar: {
      title: 'Суффиксы и приставки',
      rule: ['Кто: -er, -or, -ist (writer, actor, artist). Что: -tion, -sion, -ness, -ment, -ence (invention, decision, kindness, development, difference).', 'Какой: -ful, -less, -ous, -al, -ly, -able (useful, useless, dangerous, national, friendly, comfortable).', 'Отрицание: un-, im-, in-, dis- (unhappy, impossible, incorrect, disagree).'],
      gaps: [
        ['Thank you for your ___. (KIND)', ['kindness', 'kindly', 'kind'], 0, 'Спасибо за вашу доброту.'],
        ['This book is very ___: I learned a lot. (USE)', ['useful', 'useless', 'user'], 0, 'Эта книга очень полезная: я многое узнал.'],
        ['He works as a ___. (WRITE)', ['writer', 'writing', 'writed'], 0, 'Он работает писателем.'],
        ['It is ___ to fly without wings. (POSSIBLE)', ['impossible', 'possibly', 'possible'], 0, 'Летать без крыльев невозможно.'],
        ['The ___ of the wheel was very important. (INVENT)', ['invention', 'inventor', 'invent'], 0, 'Изобретение колеса было очень важным.'],
        ['Tigers are ___ animals. (DANGER)', ['dangerous', 'danger', 'dangerously'], 0, 'Тигры — опасные животные.'],
        ['What a ___ day! (BEAUTY)', ['beautiful', 'beauty', 'beautifully'], 0, 'Какой прекрасный день!'],
        ['They made an important ___. (DECIDE)', ['decision', 'decide', 'decisive'], 0, 'Они приняли важное решение.'],
        ['She is a very ___ businesswoman. (SUCCESS)', ['successful', 'success', 'successfully'], 0, 'Она очень успешная бизнесвумен.'],
        ['I ___ with you completely. (AGREE)', ['disagree', 'unagree', 'imagree'], 0, 'Я совершенно с тобой не согласен.'],
      ],
    },
  },
];
