import type { Unit } from '../types.js';

// Добавки по учебникам: темы English File Elementary/Pre-Intermediate, которых не хватало
// (вопросы, me/him и артикли, there was/might), и «Ситуации» — живые диалоги в духе
// Practical English (English File), Real World (Face2Face) и Speakout.

export const CLASSROOM: Unit = {
  id: 'inclass',
  title: 'Situations: in class',
  ru: 'Ситуации: на уроке',
  level: 'Starter',
  grades: [5, 6],
  icon: '🙋',
  words: [
    ['listen', 'слушать'],
    ['look', 'смотреть', '👀'],
    ['repeat', 'повторять', '🔁'],
    ['open', 'открывать'],
    ['close', 'закрывать'],
    ['sit down', 'садиться'],
    ['stand up', 'вставать с места'],
    ['answer', 'отвечать'],
    ['ask', 'спрашивать'],
    ['understand', 'понимать'],
    ['know', 'знать'],
    ['spell', 'называть по буквам', '🔤'],
    ['again', 'ещё раз'],
    ['slowly', 'медленно', '🐢'],
    ['loudly', 'громко', '📢'],
    ['question', 'вопрос', '❓'],
    ['page', 'страница', '📄'],
    ['word', 'слово'],
    ['mean', 'значить'],
    ['help', 'помогать', '🆘'],
  ],
  phrases: [
    ['Sorry, I don’t understand.', 'Извините, я не понимаю.'],
    ['Can you repeat that, please?', 'Повторите, пожалуйста.'],
    ['How do you spell it?', 'Как это пишется по буквам?'],
    ['What does this word mean?', 'Что значит это слово?'],
    ['Can you speak more slowly, please?', 'Говорите, пожалуйста, помедленнее.'],
    ['Look at the board.', 'Посмотрите на доску.'],
    ['I don’t know.', 'Я не знаю.'],
    ['Can I ask a question?', 'Можно задать вопрос?'],
    ['How do you say it in English?', 'Как это сказать по-английски?'],
    ['Sit down, please.', 'Садитесь, пожалуйста.'],
  ],
  grammar: {
    title: 'Фразы на уроке',
    rule: ['Не понял: Sorry, I don’t understand. Can you repeat that, please?', 'Слово: What does … mean? How do you spell …? How do you say … in English?', 'Просьбы учителя: Open your books. Look at the board. Sit down. Stand up.'],
    gaps: [
      ['— What does “cat” mean? — It ___ «кошка».', ['means', 'mean', 'meaning'], 0, '— Что значит cat? — Это значит «кошка».'],
      ['Sorry, I don’t ___.', ['understand', 'understands', 'understanding'], 0, 'Извините, я не понимаю.'],
      ['Can you ___ that, please?', ['repeat', 'repeats', 'repeating'], 0, 'Повторите, пожалуйста.'],
      ['How do you ___ your name?', ['spell', 'spells', 'spelling'], 0, 'Как пишется твоё имя по буквам?'],
      ['Please speak more ___.', ['slowly', 'slowness', 'slows'], 0, 'Говорите, пожалуйста, помедленнее.'],
      ['Look ___ the board, please.', ['at', 'on', 'to'], 0, 'Посмотрите на доску.'],
      ['___ I ask a question?', ['Can', 'Do', 'Am'], 0, 'Можно задать вопрос?'],
      ['I don’t ___ the answer.', ['know', 'knows', 'knowing'], 0, 'Я не знаю ответ.'],
      ['How do you say «стол» ___ English?', ['in', 'on', 'at'], 0, 'Как по-английски «стол»?'],
      ['Sit ___, please.', ['down', 'up', 'on'], 0, 'Садитесь, пожалуйста.'],
    ],
  },
};

export const QUESTIONS: Unit = {
  id: 'questions',
  title: 'Questions',
  ru: 'Вопросы',
  level: 'A1',
  grades: [5, 7],
  icon: '❓',
  words: [
    ['what', 'что'],
    ['where', 'где'],
    ['when', 'когда'],
    ['who', 'кто'],
    ['why', 'почему'],
    ['how', 'как'],
    ['how old', 'сколько лет'],
    ['how many', 'сколько (штук)'],
    ['how much', 'сколько (денег, воды)'],
    ['which', 'какой (из)'],
    ['whose', 'чей'],
    ['what time', 'во сколько'],
    ['because', 'потому что'],
    ['live', 'жить'],
    ['start', 'начинать(ся)'],
    ['finish', 'заканчивать(ся)'],
    ['favourite', 'любимый', '❤️'],
    ['birthday', 'день рождения', '🎂'],
    ['address', 'адрес', '🏠'],
    ['email', 'электронная почта', '📧'],
  ],
  phrases: [
    ['Where do you live?', 'Где ты живёшь?'],
    ['What time does the film start?', 'Во сколько начинается фильм?'],
    ['Why are you sad?', 'Почему тебе грустно?'],
    ['Who is your best friend?', 'Кто твой лучший друг?'],
    ['When is your birthday?', 'Когда у тебя день рождения?'],
    ['Which bag is yours?', 'Какой рюкзак твой?'],
    ['How do you go to school?', 'Как ты добираешься до школы?'],
    ['What is your favourite film?', 'Какой твой любимый фильм?'],
    ['How much is it?', 'Сколько это стоит?'],
    ['Because I am tired.', 'Потому что я устал.'],
  ],
  grammar: {
    title: 'Вопросы: порядок слов',
    rule: ['Схема: вопросительное слово + do / does + кто + глагол: Where do you live? What time does it start?', 'С to be и can — без do: Where is he? What can you see?', 'Если спрашиваем «кто?» о том, кто делает, — без do: Who lives here?'],
    gaps: [
      ['Where ___ you live?', ['do', 'does', 'are'], 0, 'Где ты живёшь?'],
      ['What time ___ the film start?', ['does', 'do', 'is'], 0, 'Во сколько начинается фильм?'],
      ['Why ___ you sad?', ['are', 'do', 'does'], 0, 'Почему тебе грустно?'],
      ['___ is your birthday? — In May.', ['When', 'Where', 'Who'], 0, 'Когда у тебя день рождения? — В мае.'],
      ['___ is your best friend? — Max.', ['Who', 'What', 'Which'], 0, 'Кто твой лучший друг? — Макс.'],
      ['___ do you go to school? — By bus.', ['How', 'What', 'Why'], 0, 'Как ты добираешься до школы? — На автобусе.'],
      ['___ much is this T-shirt?', ['How', 'What', 'Which'], 0, 'Сколько стоит эта футболка?'],
      ['Where does she ___?', ['work', 'works', 'working'], 0, 'Где она работает?'],
      ['___ bag is this? — It’s Tom’s.', ['Whose', 'Who', 'Who’s'], 0, 'Чей это рюкзак? — Тома.'],
      ['Who ___ in this house?', ['lives', 'does live', 'live'], 0, 'Кто живёт в этом доме?'],
    ],
  },
};

export const CAFE: Unit = {
  id: 'cafe',
  title: 'Situations: café and shop',
  ru: 'Ситуации: кафе и магазин',
  level: 'A1',
  grades: [5, 7],
  icon: '☕',
  words: [
    ['café', 'кафе', '☕'],
    ['waiter', 'официант'],
    ['bill', 'счёт', '🧾'],
    ['order', 'заказывать'],
    ['drink', 'напиток', '🥤'],
    ['dessert', 'десерт', '🍰'],
    ['salad', 'салат', '🥗'],
    ['burger', 'бургер', '🍔'],
    ['chips', 'картошка фри', '🍟'],
    ['small', 'маленький'],
    ['large', 'большой (размер)'],
    ['cash', 'наличные', '💵'],
    ['card', 'карта', '💳'],
    ['change', 'сдача', '🪙'],
    ['receipt', 'чек'],
    ['queue', 'очередь'],
    ['customer', 'покупатель'],
    ['sale', 'распродажа', '🏷️'],
    ['pay', 'платить'],
    ['take away', 'с собой', '🥡'],
  ],
  phrases: [
    ['Can I help you?', 'Чем могу помочь?'],
    ['I’d like a burger, please.', 'Мне бургер, пожалуйста.'],
    ['Anything else?', 'Что-нибудь ещё?'],
    ['That’s all, thanks.', 'Это всё, спасибо.'],
    ['Eat in or take away?', 'Здесь или с собой?'],
    ['How much is that?', 'Сколько с меня?'],
    ['Can I pay by card?', 'Можно оплатить картой?'],
    ['Here’s your change.', 'Вот ваша сдача.'],
    ['Could we have the bill, please?', 'Можно счёт, пожалуйста?'],
    ['Enjoy your meal!', 'Приятного аппетита!'],
  ],
  grammar: {
    title: 'Диалоги: заказ и покупка',
    rule: ['Вежливо попросить: I’d like… (= I would like), Could I have…?, Can I have…, please?', 'Продавец: Can I help you? Anything else? Eat in or take away?', 'Оплата: How much is it? Can I pay by card / in cash? Here’s your change.'],
    gaps: [
      ['— Can I help you? — Yes, ___ a cheeseburger, please.', ['I’d like', 'I like', 'I liking'], 0, '— Чем могу помочь? — Мне чизбургер, пожалуйста.'],
      ['— Anything else? — No, that’s ___, thanks.', ['all', 'every', 'each'], 0, '— Что-нибудь ещё? — Нет, это всё, спасибо.'],
      ['— Eat in or take ___? — Take away, please.', ['away', 'off', 'out of'], 0, '— Здесь или с собой? — С собой.'],
      ['— How ___ is that? — Five pounds.', ['much', 'many', 'often'], 0, '— Сколько с меня? — Пять фунтов.'],
      ['Can I pay ___ card?', ['by', 'on', 'at'], 0, 'Можно оплатить картой?'],
      ['Could we ___ the bill, please?', ['have', 'having', 'has'], 0, 'Можно счёт, пожалуйста?'],
      ['Here’s your ___. (сдача)', ['change', 'rest', 'back'], 0, 'Вот ваша сдача.'],
      ['Would you like ___ drink?', ['a', 'an', 'any'], 0, 'Хотите напиток?'],
      ['— Small or large? — ___, please.', ['Large', 'Larger', 'The largest'], 0, '— Маленький или большой? — Большой, пожалуйста.'],
      ['Enjoy your ___!', ['meal', 'eat', 'eating'], 0, 'Приятного аппетита!'],
    ],
  },
};

export const OBJECTS: Unit = {
  id: 'objects',
  title: 'Me, you and the…',
  ru: 'me, him и артикли',
  level: 'A2',
  grades: [6, 8],
  icon: '🎁',
  words: [
    ['me', 'меня, мне'],
    ['him', 'его, ему'],
    ['her', 'её, ей'],
    ['us', 'нас, нам'],
    ['them', 'их, им'],
    ['it', 'его, её (о предмете)'],
    ['the sun', 'солнце', '☀️'],
    ['the moon', 'луна', '🌙'],
    ['the sea', 'море', '🌊'],
    ['the radio', 'радио', '📻'],
    ['piano', 'пианино', '🎹'],
    ['call', 'звонить', '📞'],
    ['invite', 'приглашать'],
    ['send', 'отправлять', '📩'],
    ['show', 'показывать'],
    ['give', 'давать'],
    ['lend', 'одалживать (кому-то)'],
    ['borrow', 'брать взаймы'],
    ['present', 'подарок', '🎁'],
    ['together', 'вместе'],
  ],
  phrases: [
    ['Call me tonight.', 'Позвони мне вечером.'],
    ['I like him, he is funny.', 'Он мне нравится, он смешной.'],
    ['Can you help us?', 'Можешь нам помочь?'],
    ['I gave them a present.', 'Я подарил им подарок.'],
    ['The sun is very bright.', 'Солнце очень яркое.'],
    ['I play the piano.', 'Я играю на пианино.'],
    ['I listen to the radio.', 'Я слушаю радио.'],
    ['We went to the sea together.', 'Мы вместе ездили на море.'],
    ['Can you lend me a pen?', 'Одолжишь мне ручку?'],
    ['Show it to me, please.', 'Покажи мне это, пожалуйста.'],
  ],
  grammar: {
    title: 'me, him, them и артикли a / the',
    rule: ['После глагола и предлога: me, you, him, her, it, us, them: Call me. Look at them.', 'a / an — один из многих, впервые: There is an apple. the — тот самый, единственный, уже знакомый: the sun, the sea.', 'play the guitar / the piano; listen to the radio. Без артикля: имена, страны, языки — Anna, Russia, English.'],
    gaps: [
      ['Call ___ tonight. (мне)', ['me', 'I', 'my'], 0, 'Позвони мне вечером.'],
      ['I like ___. He is funny.', ['him', 'he', 'his'], 0, 'Он мне нравится. Он смешной.'],
      ['Can you help ___? (нам)', ['us', 'we', 'our'], 0, 'Можешь нам помочь?'],
      ['I gave ___ a present. (им)', ['them', 'they', 'their'], 0, 'Я подарил им подарок.'],
      ['___ sun is very bright today.', ['The', 'A', 'An'], 0, 'Сегодня очень яркое солнце.'],
      ['There is ___ apple on the table.', ['an', 'the', 'a'], 0, 'На столе лежит яблоко.'],
      ['She plays ___ piano very well.', ['the', 'a', 'an'], 0, 'Она очень хорошо играет на пианино.'],
      ['Look at ___! (на неё)', ['her', 'she', 'hers'], 0, 'Посмотри на неё!'],
      ['We swam in ___ sea every day.', ['the', 'a', 'an'], 0, 'Мы каждый день плавали в море.'],
      ['Show ___ to me, please. (это)', ['it', 'its', 'it’s'], 0, 'Покажи мне это, пожалуйста.'],
    ],
  },
};

export const MAYBE: Unit = {
  id: 'maybe',
  title: 'There was… It might…',
  ru: 'there was и «может быть»',
  level: 'A2',
  grades: [7, 9],
  icon: '🏰',
  words: [
    ['might', 'возможно (может)'],
    ['perhaps', 'пожалуй'],
    ['there was', 'был, была (там)'],
    ['there were', 'были (там)'],
    ['castle', 'замок', '🏰'],
    ['village', 'деревня', '🏘️'],
    ['ancient', 'древний'],
    ['crowd', 'толпа'],
    ['market', 'рынок'],
    ['festival', 'фестиваль', '🎪'],
    ['fireworks', 'фейерверк', '🎆'],
    ['snowstorm', 'метель', '🌨️'],
    ['surprise', 'сюрприз'],
    ['forecast', 'прогноз'],
    ['guess', 'угадывать'],
    ['sure', 'уверенный'],
    ['tonight', 'сегодня вечером'],
    ['later', 'позже'],
    ['empty', 'пустой'],
    ['full', 'полный'],
  ],
  phrases: [
    ['There was a castle on the hill.', 'На холме был замок.'],
    ['There were a lot of people at the festival.', 'На фестивале было много людей.'],
    ['Was there a market in the village?', 'В деревне был рынок?'],
    ['There weren’t any shops.', 'Магазинов не было.'],
    ['It might rain later.', 'Позже, возможно, пойдёт дождь.'],
    ['I might go to the party.', 'Может, я пойду на вечеринку.'],
    ['She may be at home.', 'Возможно, она дома.'],
    ['I’m not sure.', 'Я не уверен.'],
    ['Perhaps he is ill.', 'Пожалуй, он заболел.'],
    ['The streets were empty.', 'Улицы были пустыми.'],
  ],
  grammar: {
    title: 'there was / were; might / may',
    rule: ['В прошлом: there was + один, there were + много. Вопрос: Was there…? Were there…?', 'might / may + глагол — возможно, может быть: It might rain. She may be late.', 'Нет: might not / may not. Сравни: will — уверен, might — не уверен.'],
    gaps: [
      ['There ___ a castle here 500 years ago.', ['was', 'were', 'is'], 0, '500 лет назад здесь был замок.'],
      ['There ___ lots of people at the festival yesterday.', ['were', 'was', 'are'], 0, 'Вчера на фестивале было много людей.'],
      ['___ there a market in the village then?', ['Was', 'Were', 'Did'], 0, 'Тогда в деревне был рынок?'],
      ['There ___ any shops in the village.', ['weren’t', 'wasn’t', 'didn’t'], 0, 'В деревне не было магазинов.'],
      ['Take an umbrella. It ___ rain later.', ['might', 'mights', 'might to'], 0, 'Возьми зонт. Позже, возможно, пойдёт дождь.'],
      ['I might ___ to the party.', ['go', 'to go', 'going'], 0, 'Может, я пойду на вечеринку.'],
      ['She ___ be at home, I’m not sure.', ['may', 'mays', 'is may'], 0, 'Возможно, она дома, не уверен.'],
      ['We might ___ come. We are busy.', ['not', 'don’t', 'no'], 0, 'Мы, возможно, не придём. Мы заняты.'],
      ['I’m not ___. Perhaps she is ill.', ['sure', 'surely', 'sured'], 0, 'Я не уверен. Может, она заболела.'],
      ['Were there any fireworks? — Yes, there ___.', ['were', 'was', 'did'], 0, 'Был фейерверк? — Да.'],
    ],
  },
};

export const HOTEL: Unit = {
  id: 'trips',
  title: 'Situations: hotel and airport',
  ru: 'Ситуации: гостиница и вокзал',
  level: 'A2',
  grades: [7, 9],
  icon: '🛎️',
  words: [
    ['reception', 'стойка администратора', '🛎️'],
    ['room key', 'ключ от номера', '🔑'],
    ['single room', 'одноместный номер'],
    ['double room', 'двухместный номер'],
    ['reservation', 'бронь'],
    ['check in', 'заселяться'],
    ['check out', 'выезжать'],
    ['luggage', 'багаж', '🧳'],
    ['lift', 'лифт', '🛗'],
    ['towel', 'полотенце'],
    ['Wi-Fi password', 'пароль от вайфая', '📶'],
    ['boarding pass', 'посадочный талон', '🎫'],
    ['gate', 'выход на посадку'],
    ['flight', 'рейс', '✈️'],
    ['delay', 'задержка', '⏳'],
    ['departure', 'отправление', '🛫'],
    ['arrival', 'прибытие', '🛬'],
    ['platform', 'платформа', '🚉'],
    ['single ticket', 'билет в одну сторону'],
    ['return ticket', 'билет туда и обратно'],
  ],
  phrases: [
    ['I have a reservation for two nights.', 'У меня бронь на две ночи.'],
    ['What time is check-out?', 'Во сколько выезд?'],
    ['Is breakfast included?', 'Завтрак включён?'],
    ['Could I have another towel, please?', 'Можно ещё одно полотенце?'],
    ['What’s the Wi-Fi password?', 'Какой пароль от вайфая?'],
    ['The lift isn’t working.', 'Лифт не работает.'],
    ['Where is gate twelve?', 'Где выход двенадцать?'],
    ['Our flight is delayed.', 'Наш рейс задерживается.'],
    ['A return ticket to Oxford, please.', 'Билет до Оксфорда туда и обратно, пожалуйста.'],
    ['Which platform does the train leave from?', 'С какой платформы отходит поезд?'],
  ],
  grammar: {
    title: 'Диалоги в поездке',
    rule: ['Гостиница: I have a reservation. What time is check-in / check-out? Is breakfast included?', 'Просьба: Could I have another towel, please? The lift isn’t working.', 'Транспорт: A single / return ticket to…, please. Which platform…? The flight is delayed.'],
    gaps: [
      ['I have a ___ for two nights.', ['reservation', 'reserve', 'reserving'], 0, 'У меня бронь на две ночи.'],
      ['What time is ___? (выезд)', ['check-out', 'check-in', 'checking'], 0, 'Во сколько выезд?'],
      ['Is breakfast ___?', ['included', 'include', 'including'], 0, 'Завтрак включён?'],
      ['Could I have ___ towel, please?', ['another', 'other', 'others'], 0, 'Можно ещё одно полотенце?'],
      ['The lift ___ working.', ['isn’t', 'doesn’t', 'not'], 0, 'Лифт не работает.'],
      ['Our flight is ___ by two hours.', ['delayed', 'delay', 'delaying'], 0, 'Наш рейс задерживается на два часа.'],
      ['Which platform does the train leave ___?', ['from', 'of', 'at'], 0, 'С какой платформы отходит поезд?'],
      ['— Single or return? — ___, please. I’m coming back tomorrow.', ['Return', 'Single', 'Double'], 0, '— В одну сторону или обратно? — Туда и обратно, я завтра возвращаюсь.'],
      ['Please show your ___ at the gate.', ['boarding pass', 'boarding', 'pass board'], 0, 'Покажите посадочный талон у выхода.'],
      ['Where can I ___ my luggage?', ['leave', 'leaving', 'to leave'], 0, 'Где можно оставить багаж?'],
    ],
  },
};

export const OPINION: Unit = {
  id: 'opinion',
  title: 'Situations: opinions',
  ru: 'Ситуации: мнение и спор (ОГЭ)',
  level: 'B1',
  grades: [8, 11],
  icon: '🗣️',
  words: [
    ['opinion', 'мнение'],
    ['in my opinion', 'по-моему'],
    ['I agree', 'я согласен'],
    ['I disagree', 'я не согласен'],
    ['on the one hand', 'с одной стороны'],
    ['on the other hand', 'с другой стороны'],
    ['however', 'однако'],
    ['although', 'хотя'],
    ['advantage', 'преимущество'],
    ['disadvantage', 'недостаток'],
    ['argument', 'довод'],
    ['point of view', 'точка зрения'],
    ['to be honest', 'честно говоря'],
    ['for example', 'например'],
    ['firstly', 'во-первых'],
    ['moreover', 'более того'],
    ['suggest', 'предлагать'],
    ['recommend', 'рекомендовать'],
    ['exactly', 'именно, точно'],
    ['debate', 'дебаты'],
  ],
  phrases: [
    ['In my opinion, school uniform is a good idea.', 'По-моему, школьная форма — хорошая идея.'],
    ['I totally agree with you.', 'Полностью с тобой согласен.'],
    ['I see your point, but I disagree.', 'Я понимаю твою мысль, но не согласен.'],
    ['On the one hand, phones are useful.', 'С одной стороны, телефоны полезны.'],
    ['On the other hand, they can be distracting.', 'С другой стороны, они могут отвлекать.'],
    ['What do you think about it?', 'Что ты об этом думаешь?'],
    ['To be honest, I don’t like it.', 'Честно говоря, мне это не нравится.'],
    ['That’s a good point.', 'Хорошее замечание.'],
    ['I suggest going by train.', 'Предлагаю поехать на поезде.'],
    ['Although it was raining, we went out.', 'Хотя шёл дождь, мы вышли на улицу.'],
  ],
  grammar: {
    title: 'Как выразить мнение (письмо и устная часть ОГЭ)',
    rule: ['Мнение: In my opinion…, I think…, I believe…, As far as I know…', 'Согласие и несогласие: I agree with you. I’m afraid I disagree. That’s true, but…', 'Связки: firstly, moreover, however, although, on the one hand / on the other hand.', 'suggest / recommend + -ing: I suggest going. I recommend reading it.'],
    gaps: [
      ['___ my opinion, it’s a great idea.', ['In', 'On', 'At'], 0, 'По-моему, это отличная идея.'],
      ['I totally agree ___ you.', ['with', 'to', 'for'], 0, 'Полностью с тобой согласен.'],
      ['On the one hand, it’s cheap. On the ___ hand, it’s slow.', ['other', 'another', 'second'], 0, 'С одной стороны, это дёшево. С другой — медленно.'],
      ['I suggest ___ by train.', ['going', 'to go', 'go'], 0, 'Предлагаю поехать на поезде.'],
      ['___ it was raining, we went for a walk.', ['Although', 'However', 'Despite'], 0, 'Хотя шёл дождь, мы пошли гулять.'],
      ['It’s expensive. ___, it’s very good.', ['However', 'Although', 'Despite'], 0, 'Это дорого. Однако это очень хорошо.'],
      ['What do you think ___ it?', ['about', 'on', 'for'], 0, 'Что ты об этом думаешь?'],
      ['To be ___, I don’t like it.', ['honest', 'honestly', 'honesty'], 0, 'Честно говоря, мне это не нравится.'],
      ['I recommend ___ this book.', ['reading', 'to read', 'read'], 0, 'Рекомендую прочитать эту книгу.'],
      ['That’s a good ___. (замечание)', ['point', 'opinion', 'idea'], 0, 'Хорошее замечание.'],
    ],
  },
};
