import type { Unit } from '../types.js';

// Starter (с нуля): знакомство, цвета и числа, вещи, животные, тело, семья, еда, «я умею».
export const STARTER: Unit[] = [
  {
    id: 'hi',
    title: 'Hello!',
    ru: 'Привет!',
    level: 'Starter',
    grades: [5, 6],
    icon: '👋',
    words: [
      ['hello', 'привет', '👋'],
      ['goodbye', 'до свидания'],
      ['bye', 'пока'],
      ['good morning', 'доброе утро', '🌅'],
      ['good night', 'спокойной ночи', '🌙'],
      ['name', 'имя', '🏷️'],
      ['friend', 'друг', '🤝'],
      ['boy', 'мальчик', '👦'],
      ['girl', 'девочка', '👧'],
      ['teacher', 'учитель', '🧑‍🏫'],
      ['pupil', 'ученик', '🧒'],
      ['man', 'мужчина', '👨'],
      ['woman', 'женщина', '👩'],
      ['yes', 'да'],
      ['no', 'нет'],
      ['please', 'пожалуйста'],
      ['thank you', 'спасибо'],
      ['sorry', 'извини'],
      ['happy', 'счастливый', '😊'],
      ['sad', 'грустный', '😢'],
    ],
    phrases: [
      ['Hello! I am Tom.', 'Привет! Я Том.'],
      ['What is your name?', 'Как тебя зовут?'],
      ['My name is Kate.', 'Меня зовут Кейт.'],
      ['How are you?', 'Как дела?'],
      ['I am fine, thank you.', 'Хорошо, спасибо.'],
      ['Nice to meet you.', 'Приятно познакомиться.'],
      ['This is my friend.', 'Это мой друг.'],
      ['Are you a pupil?', 'Ты ученик?'],
      ['I am not sad.', 'Мне не грустно.'],
      ['Goodbye, see you!', 'До свидания, увидимся!'],
    ],
    grammar: {
      title: 'I am, you are',
      rule: ['I am (= I’m) — я: I am Tom.', 'you are (= you’re) — ты, вы: You are my friend.', 'Вопрос — глагол вперёд: Are you a pupil? — Yes, I am. / No, I’m not.', 'Отрицание — not: I am not sad.'],
      gaps: [
        ['I ___ Tom.', ['am', 'are', 'is'], 0, 'Я Том.'],
        ['You ___ my friend.', ['are', 'am', 'is'], 0, 'Ты мой друг.'],
        ['___ you a pupil?', ['Are', 'Am', 'Is'], 0, 'Ты ученик?'],
        ['Yes, I ___.', ['am', 'are', 'is'], 0, 'Да (я ученик).'],
        ['I ___ happy today.', ['am', 'are', 'be'], 0, 'Я сегодня счастлив.'],
        ['You ___ a good teacher.', ['are', 'am', 'is'], 0, 'Вы хороший учитель.'],
        ['___ name is Kate.', ['My', 'I', 'Me'], 0, 'Меня зовут Кейт.'],
        ['What is ___ name?', ['your', 'you', 'you’re'], 0, 'Как тебя зовут?'],
        ['I am ___ sad.', ['not', 'no', 'don’t'], 0, 'Мне не грустно.'],
        ['Nice to ___ you.', ['meet', 'meets', 'meeting'], 0, 'Приятно познакомиться.'],
      ],
    },
  },
  {
    id: 'colours',
    title: 'Colours and numbers',
    ru: 'Цвета и числа',
    level: 'Starter',
    grades: [5, 6],
    icon: '🎨',
    words: [
      ['red', 'красный', '🔴'],
      ['blue', 'синий', '🔵'],
      ['green', 'зелёный', '🟢'],
      ['yellow', 'жёлтый', '🟡'],
      ['black', 'чёрный', '⚫'],
      ['white', 'белый', '⚪'],
      ['orange', 'оранжевый', '🟠'],
      ['brown', 'коричневый', '🟤'],
      ['purple', 'фиолетовый', '🟣'],
      ['pink', 'розовый'],
      ['grey', 'серый'],
      ['colour', 'цвет'],
      ['five', 'пять', '5️⃣'],
      ['six', 'шесть', '6️⃣'],
      ['seven', 'семь', '7️⃣'],
      ['eight', 'восемь', '8️⃣'],
      ['nine', 'девять', '9️⃣'],
      ['ten', 'десять', '🔟'],
      ['twelve', 'двенадцать'],
      ['twenty', 'двадцать'],
    ],
    phrases: [
      ['What colour is it?', 'Какого это цвета?'],
      ['It is red.', 'Это красный.'],
      ['My bag is blue.', 'Мой рюкзак синий.'],
      ['I like green.', 'Я люблю зелёный цвет.'],
      ['How many pens?', 'Сколько ручек?'],
      ['Seven pens.', 'Семь ручек.'],
      ['I am ten.', 'Мне десять лет.'],
      ['How old are you?', 'Сколько тебе лет?'],
      ['The sky is blue.', 'Небо голубое.'],
      ['Count to twenty!', 'Посчитай до двадцати!'],
    ],
    grammar: {
      title: 'It is… и How many…?',
      rule: ['It is (= it’s) — это: It is red. It’s a pen.', 'Сколько? — How many + множественное число: How many cats?', 'Возраст — через am/is/are: I am ten. How old are you?'],
      gaps: [
        ['It ___ green.', ['is', 'are', 'am'], 0, 'Это зелёное.'],
        ['How ___ pens have you got?', ['many', 'much', 'old'], 0, 'Сколько у тебя ручек?'],
        ['How ___ are you?', ['old', 'many', 'much'], 0, 'Сколько тебе лет?'],
        ['I ___ eleven.', ['am', 'is', 'are'], 0, 'Мне одиннадцать.'],
        ['Five and five is ___.', ['ten', 'nine', 'twelve'], 0, 'Пять и пять — десять.'],
        ['Two and six is ___.', ['eight', 'seven', 'six'], 0, 'Два и шесть — восемь.'],
        ['What colour ___ your bag?', ['is', 'are', 'am'], 0, 'Какого цвета твой рюкзак?'],
        ['Bananas are ___.', ['yellow', 'blue', 'black'], 0, 'Бананы жёлтые.'],
        ['Snow is ___.', ['white', 'black', 'green'], 0, 'Снег белый.'],
        ['Grass is ___.', ['green', 'pink', 'purple'], 0, 'Трава зелёная.'],
      ],
    },
  },
  {
    id: 'things',
    title: 'My things',
    ru: 'Мои вещи',
    level: 'Starter',
    grades: [5, 6],
    icon: '🎒',
    words: [
      ['book', 'книга', '📕'],
      ['pen', 'ручка', '🖊️'],
      ['pencil', 'карандаш', '✏️'],
      ['bag', 'рюкзак', '🎒'],
      ['ruler', 'линейка', '📏'],
      ['rubber', 'ластик'],
      ['desk', 'парта'],
      ['chair', 'стул', '🪑'],
      ['ball', 'мяч', '⚽'],
      ['doll', 'кукла', '🪆'],
      ['car', 'машинка', '🚗'],
      ['kite', 'воздушный змей', '🪁'],
      ['teddy bear', 'плюшевый мишка', '🧸'],
      ['computer', 'компьютер', '💻'],
      ['phone', 'телефон', '📱'],
      ['clock', 'часы (настенные)', '🕒'],
      ['watch', 'часы (наручные)', '⌚'],
      ['box', 'коробка', '📦'],
      ['umbrella', 'зонт', '☂️'],
      ['robot', 'робот', '🤖'],
    ],
    phrases: [
      ['This is my pen.', 'Это моя ручка.'],
      ['That is your bag.', 'Вон тот рюкзак — твой.'],
      ['What is this?', 'Что это?'],
      ['It is a robot.', 'Это робот.'],
      ['Is this your phone?', 'Это твой телефон?'],
      ['I have a new ball.', 'У меня новый мяч.'],
      ['Where is my ruler?', 'Где моя линейка?'],
      ['Here you are.', 'Вот, держи.'],
      ['Can I have a pencil, please?', 'Можно мне карандаш?'],
      ['My teddy bear is brown.', 'Мой мишка коричневый.'],
    ],
    grammar: {
      title: 'this / that, a / an',
      rule: ['this — это (рядом со мной): This is a pen.', 'that — вон то (далеко): That is a kite.', 'an — перед гласным звуком: an umbrella, an apple. a — перед согласным: a ball, a robot.'],
      gaps: [
        ['___ is my pen. (у меня в руке)', ['This', 'That', 'These'], 0, 'Это моя ручка.'],
        ['___ is a kite. (вон там, в небе)', ['That', 'This', 'These'], 0, 'Вон там воздушный змей.'],
        ['It is ___ umbrella.', ['an', 'a', 'two'], 0, 'Это зонт.'],
        ['It is ___ robot.', ['a', 'an', 'two'], 0, 'Это робот.'],
        ['I have ___ apple.', ['an', 'a', 'two'], 0, 'У меня есть яблоко.'],
        ['This is ___ old car.', ['an', 'a', 'two'], 0, 'Это старая машинка.'],
        ['What is ___? (предмет у меня в руке)', ['this', 'these', 'those'], 0, 'Что это?'],
        ['This is ___ watch.', ['my', 'me', 'I'], 0, 'Это мои часы.'],
        ['That is ___ teddy bear.', ['your', 'you', 'you’re'], 0, 'Вон тот мишка — твой.'],
        ['Here ___ are.', ['you', 'your', 'yours'], 0, 'Вот, держи.'],
      ],
    },
  },
  {
    id: 'animals',
    title: 'Animals',
    ru: 'Животные',
    level: 'Starter',
    grades: [5, 6],
    icon: '🐾',
    words: [
      ['cat', 'кошка', '🐱'],
      ['dog', 'собака', '🐶'],
      ['bird', 'птица', '🐦'],
      ['horse', 'лошадь', '🐴'],
      ['cow', 'корова', '🐄'],
      ['pig', 'свинья', '🐷'],
      ['sheep', 'овца', '🐑'],
      ['duck', 'утка', '🦆'],
      ['rabbit', 'кролик', '🐰'],
      ['mouse', 'мышь', '🐭'],
      ['frog', 'лягушка', '🐸'],
      ['lion', 'лев', '🦁'],
      ['tiger', 'тигр', '🐯'],
      ['monkey', 'обезьяна', '🐒'],
      ['elephant', 'слон', '🐘'],
      ['bear', 'медведь', '🐻'],
      ['giraffe', 'жираф', '🦒'],
      ['snake', 'змея', '🐍'],
      ['zebra', 'зебра', '🦓'],
      ['fox', 'лиса', '🦊'],
    ],
    phrases: [
      ['I have got a cat.', 'У меня есть кошка.'],
      ['Dogs can run.', 'Собаки умеют бегать.'],
      ['Look at the monkey!', 'Посмотри на обезьяну!'],
      ['Elephants are big.', 'Слоны большие.'],
      ['The mouse is small.', 'Мышь маленькая.'],
      ['My rabbit is white.', 'Мой кролик белый.'],
      ['Lions live in Africa.', 'Львы живут в Африке.'],
      ['I like horses.', 'Я люблю лошадей.'],
      ['The frog is green.', 'Лягушка зелёная.'],
      ['Birds can fly.', 'Птицы умеют летать.'],
    ],
    grammar: {
      title: 'Множественное число',
      rule: ['Обычно + s: cat → cats, dog → dogs.', 'После s, x, sh, ch + es: fox → foxes, box → boxes.', 'Особые слова: mouse → mice, man → men, child → children; sheep и fish не меняются.'],
      gaps: [
        ['two ___', ['cats', 'cat', 'cates'], 0, 'две кошки'],
        ['three ___', ['foxes', 'foxs', 'fox'], 0, 'три лисы'],
        ['four ___', ['mice', 'mouses', 'mouse'], 0, 'четыре мыши'],
        ['five ___', ['sheep', 'sheeps', 'sheepes'], 0, 'пять овец'],
        ['two big ___', ['horses', 'horse', 'horsies'], 0, 'две большие лошади'],
        ['ten ___', ['children', 'childs', 'childrens'], 0, 'десять детей'],
        ['six ___', ['boxes', 'boxs', 'box'], 0, 'шесть коробок'],
        ['two ___', ['men', 'mans', 'mens'], 0, 'двое мужчин'],
        ['three ___', ['monkeys', 'monkies', 'monkey'], 0, 'три обезьяны'],
        ['Elephants ___ big.', ['are', 'is', 'am'], 0, 'Слоны большие.'],
      ],
    },
  },
  {
    id: 'body',
    title: 'My body',
    ru: 'Тело и внешность',
    level: 'Starter',
    grades: [5, 6],
    icon: '🧍',
    words: [
      ['head', 'голова'],
      ['face', 'лицо', '🙂'],
      ['eye', 'глаз', '👁️'],
      ['ear', 'ухо', '👂'],
      ['nose', 'нос', '👃'],
      ['mouth', 'рот', '👄'],
      ['hair', 'волосы', '💇'],
      ['hand', 'кисть руки', '✋'],
      ['arm', 'рука (от плеча)', '💪'],
      ['leg', 'нога', '🦵'],
      ['foot', 'ступня', '🦶'],
      ['teeth', 'зубы', '🦷'],
      ['finger', 'палец', '☝️'],
      ['knee', 'колено'],
      ['neck', 'шея'],
      ['back', 'спина'],
      ['tall', 'высокий'],
      ['short', 'невысокий'],
      ['long', 'длинный'],
      ['big', 'большой'],
    ],
    phrases: [
      ['I have got blue eyes.', 'У меня голубые глаза.'],
      ['She has got long hair.', 'У неё длинные волосы.'],
      ['Touch your nose!', 'Дотронься до носа!'],
      ['My leg hurts.', 'У меня болит нога.'],
      ['Clap your hands!', 'Похлопай в ладоши!'],
      ['He is tall.', 'Он высокий.'],
      ['Open your mouth.', 'Открой рот.'],
      ['I brush my teeth.', 'Я чищу зубы.'],
      ['Monsters have got big ears.', 'У монстров большие уши.'],
      ['Wash your face.', 'Умой лицо.'],
    ],
    grammar: {
      title: 'have got / has got',
      rule: ['I / you / we / they have got: I have got two ears.', 'he / she / it has got: She has got blue eyes.', 'Нет: I haven’t got, he hasn’t got. Вопрос: Have you got…? Has he got…?'],
      gaps: [
        ['I ___ got two hands.', ['have', 'has', 'am'], 0, 'У меня две руки.'],
        ['She ___ got long hair.', ['has', 'have', 'is'], 0, 'У неё длинные волосы.'],
        ['The cat ___ got green eyes.', ['has', 'have', 'are'], 0, 'У кошки зелёные глаза.'],
        ['We ___ got big ears.', ['have', 'has', 'is'], 0, 'У нас большие уши.'],
        ['___ you got a dog?', ['Have', 'Has', 'Are'], 0, 'У тебя есть собака?'],
        ['___ he got a sister?', ['Has', 'Have', 'Is'], 0, 'У него есть сестра?'],
        ['I ___ got a cat.', ['haven’t', 'hasn’t', 'not'], 0, 'У меня нет кошки.'],
        ['He ___ got a bike.', ['hasn’t', 'haven’t', 'isn’t'], 0, 'У него нет велосипеда.'],
        ['They ___ got blue eyes.', ['have', 'has', 'is'], 0, 'У них голубые глаза.'],
        ['Have you got a pen? — Yes, I ___.', ['have', 'has', 'am'], 0, 'Да, есть.'],
      ],
    },
  },
  {
    id: 'myfamily',
    title: 'My family',
    ru: 'Моя семья',
    level: 'Starter',
    grades: [5, 6],
    icon: '🏠',
    words: [
      ['mother', 'мама', '👩'],
      ['father', 'папа', '👨'],
      ['sister', 'сестра', '👧'],
      ['brother', 'брат', '👦'],
      ['grandmother', 'бабушка', '👵'],
      ['grandfather', 'дедушка', '👴'],
      ['baby', 'малыш', '👶'],
      ['parents', 'родители'],
      ['aunt', 'тётя'],
      ['uncle', 'дядя'],
      ['cousin', 'двоюродный брат или сестра'],
      ['son', 'сын'],
      ['daughter', 'дочь'],
      ['family', 'семья'],
      ['house', 'дом', '🏠'],
      ['pet', 'домашний питомец', '🐾'],
      ['old', 'старый'],
      ['young', 'молодой'],
      ['kind', 'добрый'],
      ['funny', 'смешной', '😂'],
    ],
    phrases: [
      ['This is my mum.', 'Это моя мама.'],
      ['I have got a little brother.', 'У меня есть младший брат.'],
      ['My dad is a doctor.', 'Мой папа врач.'],
      ['My grandmother is kind.', 'Моя бабушка добрая.'],
      ['Her name is Anna.', 'Её зовут Анна.'],
      ['His name is Max.', 'Его зовут Макс.'],
      ['We live in a big house.', 'Мы живём в большом доме.'],
      ['Have you got a pet?', 'У тебя есть питомец?'],
      ['Our cat is funny.', 'Наша кошка смешная.'],
      ['I love my family.', 'Я люблю свою семью.'],
    ],
    grammar: {
      title: 'my, your, his, her… и ’s',
      rule: ['my — мой, your — твой, his — его, her — её, its — его/её (о животном или предмете), our — наш, their — их.', 'Чей? — ’s: Kate’s bag — рюкзак Кейт, my mum’s car — машина мамы.'],
      gaps: [
        ['This is ___ sister. (моя)', ['my', 'me', 'I'], 0, 'Это моя сестра.'],
        ['___ name is Tom. (его)', ['His', 'He', 'Him'], 0, 'Его зовут Том.'],
        ['___ name is Anna. (её)', ['Her', 'She', 'Hers'], 0, 'Её зовут Анна.'],
        ['___ house is big. (наш)', ['Our', 'We', 'Us'], 0, 'Наш дом большой.'],
        ['Is this ___ dog? (твоя)', ['your', 'you', 'you’re'], 0, 'Это твоя собака?'],
        ['___ car is red. (их)', ['Their', 'They', 'Them'], 0, 'Их машина красная.'],
        ['This is ___ bag. (рюкзак Кейт)', ['Kate’s', 'Kates', 'Kate'], 0, 'Это рюкзак Кейт.'],
        ['The dog likes ___ ball. (свой — собаки)', ['its', 'it’s', 'it'], 0, 'Собака любит свой мяч.'],
        ['My ___ name is Max. (брата)', ['brother’s', 'brothers', 'brother'], 0, 'Моего брата зовут Макс.'],
        ['Where are ___ parents? (твои)', ['your', 'you', 'yours'], 0, 'Где твои родители?'],
      ],
    },
  },
  {
    id: 'yummy',
    title: 'Yummy!',
    ru: 'Еда, которую я люблю',
    level: 'Starter',
    grades: [5, 6],
    icon: '🍎',
    words: [
      ['apple', 'яблоко', '🍎'],
      ['banana', 'банан', '🍌'],
      ['orange', 'апельсин', '🍊'],
      ['bread', 'хлеб', '🍞'],
      ['milk', 'молоко', '🥛'],
      ['water', 'вода', '💧'],
      ['juice', 'сок', '🧃'],
      ['cheese', 'сыр', '🧀'],
      ['egg', 'яйцо', '🥚'],
      ['chicken', 'курица', '🍗'],
      ['soup', 'суп', '🍲'],
      ['pizza', 'пицца', '🍕'],
      ['cake', 'торт', '🎂'],
      ['ice cream', 'мороженое', '🍦'],
      ['sweets', 'конфеты', '🍬'],
      ['tea', 'чай', '🍵'],
      ['carrot', 'морковь', '🥕'],
      ['potato', 'картофель', '🥔'],
      ['tomato', 'помидор', '🍅'],
      ['sandwich', 'бутерброд', '🥪'],
    ],
    phrases: [
      ['I like apples.', 'Я люблю яблоки.'],
      ['I don’t like milk.', 'Я не люблю молоко.'],
      ['Do you like pizza?', 'Ты любишь пиццу?'],
      ['Yes, I do.', 'Да, люблю.'],
      ['Can I have some water, please?', 'Можно мне воды, пожалуйста?'],
      ['I am hungry.', 'Я голоден.'],
      ['This cake is yummy!', 'Этот торт очень вкусный!'],
      ['My favourite food is pizza.', 'Моя любимая еда — пицца.'],
      ['She likes carrots.', 'Она любит морковь.'],
      ['Let’s have lunch.', 'Давай пообедаем.'],
    ],
    grammar: {
      title: 'like / likes / don’t like',
      rule: ['I / you / we / they like: I like cake.', 'he / she / it likes (+s!): She likes juice.', 'Не люблю: I don’t like, she doesn’t like. Вопрос: Do you like…? Does she like…?'],
      gaps: [
        ['I ___ bananas.', ['like', 'likes', 'liking'], 0, 'Я люблю бананы.'],
        ['She ___ cheese.', ['likes', 'like', 'liking'], 0, 'Она любит сыр.'],
        ['I ___ like milk.', ['don’t', 'doesn’t', 'not'], 0, 'Я не люблю молоко.'],
        ['He ___ like soup.', ['doesn’t', 'don’t', 'isn’t'], 0, 'Он не любит суп.'],
        ['___ you like pizza?', ['Do', 'Does', 'Are'], 0, 'Ты любишь пиццу?'],
        ['___ your sister like tea?', ['Does', 'Do', 'Is'], 0, 'Твоя сестра любит чай?'],
        ['Do you like cake? — Yes, I ___.', ['do', 'does', 'am'], 0, 'Да, люблю.'],
        ['Does he like sweets? — No, he ___.', ['doesn’t', 'don’t', 'isn’t'], 0, 'Нет, не любит.'],
        ['We ___ ice cream.', ['like', 'likes', 'are like'], 0, 'Мы любим мороженое.'],
        ['My cat ___ fish.', ['likes', 'like', 'liking'], 0, 'Моя кошка любит рыбу.'],
      ],
    },
  },
  {
    id: 'ican',
    title: 'I can!',
    ru: 'Я умею!',
    level: 'Starter',
    grades: [5, 6],
    icon: '🤸',
    words: [
      ['run', 'бегать', '🏃'],
      ['jump', 'прыгать'],
      ['swim', 'плавать', '🏊'],
      ['fly', 'летать', '✈️'],
      ['sing', 'петь', '🎤'],
      ['dance', 'танцевать', '💃'],
      ['draw', 'рисовать', '🎨'],
      ['read', 'читать', '📖'],
      ['write', 'писать', '✍️'],
      ['climb', 'лазать', '🧗'],
      ['ride a bike', 'кататься на велосипеде', '🚲'],
      ['skate', 'кататься на коньках', '⛸️'],
      ['ski', 'кататься на лыжах', '⛷️'],
      ['play', 'играть'],
      ['cook', 'готовить', '🍳'],
      ['count', 'считать', '🔢'],
      ['catch', 'ловить'],
      ['throw', 'бросать'],
      ['walk', 'ходить пешком', '🚶'],
      ['speak', 'говорить', '🗣️'],
    ],
    phrases: [
      ['I can swim.', 'Я умею плавать.'],
      ['I can’t ski.', 'Я не умею кататься на лыжах.'],
      ['Can you dance?', 'Ты умеешь танцевать?'],
      ['Yes, I can.', 'Да, умею.'],
      ['Birds can fly.', 'Птицы умеют летать.'],
      ['Fish can’t walk.', 'Рыбы не умеют ходить.'],
      ['She can sing very well.', 'Она очень хорошо поёт.'],
      ['Can you ride a bike?', 'Ты умеешь кататься на велосипеде?'],
      ['Let’s play football!', 'Давай поиграем в футбол!'],
      ['I can count to twenty.', 'Я умею считать до двадцати.'],
    ],
    grammar: {
      title: 'can / can’t',
      rule: ['can + глагол без to и без -s: I can swim. She can sing.', 'Не умею: can’t (= cannot).', 'Вопрос: Can you…? — Yes, I can. / No, I can’t.'],
      gaps: [
        ['I can ___.', ['swim', 'swims', 'swimming'], 0, 'Я умею плавать.'],
        ['She can ___ well.', ['sing', 'sings', 'to sing'], 0, 'Она хорошо поёт.'],
        ['___ you dance?', ['Can', 'Do', 'Are'], 0, 'Ты умеешь танцевать?'],
        ['Fish ___ walk.', ['can’t', 'don’t can', 'not can'], 0, 'Рыбы не умеют ходить.'],
        ['Can you ski? — No, I ___.', ['can’t', 'don’t', 'not'], 0, 'Нет, не умею.'],
        ['Can he ride a bike? — Yes, he ___.', ['can', 'does', 'is'], 0, 'Да, умеет.'],
        ['My brother can ___ fast.', ['run', 'runs', 'running'], 0, 'Мой брат умеет быстро бегать.'],
        ['Birds can ___.', ['fly', 'flies', 'to fly'], 0, 'Птицы умеют летать.'],
        ['We ___ play football.', ['can', 'cans', 'are can'], 0, 'Мы умеем играть в футбол.'],
        ['Can ___ draw? (она)', ['she', 'her', 'hers'], 0, 'Она умеет рисовать?'],
      ],
    },
  },
];
